/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.textmagic.sdk.model.MessageFile;
import com.textmagic.sdk.model.MessagePayload;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * Conversation
 */

public class Conversation {
  @SerializedName("id")
  private Integer id = null;

  /**
   * Message type: inbound or outbound. 
   */
  @JsonAdapter(DirectionEnum.Adapter.class)
  public enum DirectionEnum {
    IN("in"),
    
    OUT("out"),
    
    O("o"),
    
    I("i");

    private String value;

    DirectionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DirectionEnum fromValue(String text) {
      for (DirectionEnum b : DirectionEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DirectionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DirectionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DirectionEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DirectionEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("direction")
  private DirectionEnum direction = null;

  @SerializedName("sender")
  private String sender = null;

  @SerializedName("messageTime")
  private OffsetDateTime messageTime = null;

  @SerializedName("text")
  private String text = null;

  @SerializedName("receiver")
  private String receiver = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("sessionId")
  private Integer sessionId = null;

  @SerializedName("initiatorId")
  private Integer initiatorId = null;

  @SerializedName("messageFileId")
  private Integer messageFileId = null;

  /**
   * Message type.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    TEXT("text"),
    
    IMAGE("image"),
    
    AUDIO("audio"),
    
    VOICE("voice"),
    
    DOCUMENT("document"),
    
    VIDEO("video"),
    
    LOG("log"),
    
    INITIAL("initial"),
    
    NOTE("note");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  /**
   * Chat type.
   */
  @JsonAdapter(ChatTypeEnum.Adapter.class)
  public enum ChatTypeEnum {
    SMS("sms"),
    
    FACEBOOK_MESSENGER("facebook_messenger"),
    
    INSTAGRAM("instagram"),
    
    WHATSAPP_BUSINESS("whatsapp_business"),
    
    LIVE_CHAT("live_chat");

    private String value;

    ChatTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ChatTypeEnum fromValue(String text) {
      for (ChatTypeEnum b : ChatTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ChatTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ChatTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ChatTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ChatTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("chatType")
  private ChatTypeEnum chatType = null;

  @SerializedName("chatId")
  private Integer chatId = null;

  @SerializedName("isEdited")
  private Boolean isEdited = null;

  @SerializedName("errorCode")
  private String errorCode = null;

  @SerializedName("files")
  private List<MessageFile> files = null;

  @SerializedName("payload")
  private MessagePayload payload = null;

  @SerializedName("avatar")
  private String avatar = null;

  public Conversation id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "1", required = true, value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Conversation direction(DirectionEnum direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Message type: inbound or outbound. 
   * @return direction
  **/
  @ApiModelProperty(example = "in", required = true, value = "Message type: inbound or outbound. ")
  public DirectionEnum getDirection() {
    return direction;
  }

  public void setDirection(DirectionEnum direction) {
    this.direction = direction;
  }

  public Conversation sender(String sender) {
    this.sender = sender;
    return this;
  }

   /**
   * Sender phone number.
   * @return sender
  **/
  @ApiModelProperty(example = "447860021130", required = true, value = "Sender phone number.")
  public String getSender() {
    return sender;
  }

  public void setSender(String sender) {
    this.sender = sender;
  }

  public Conversation messageTime(OffsetDateTime messageTime) {
    this.messageTime = messageTime;
    return this;
  }

   /**
   * Time when  the message arrived at Textmagic.
   * @return messageTime
  **/
  @ApiModelProperty(example = "2012-11-28T18:38:28+0000", required = true, value = "Time when  the message arrived at Textmagic.")
  public OffsetDateTime getMessageTime() {
    return messageTime;
  }

  public void setMessageTime(OffsetDateTime messageTime) {
    this.messageTime = messageTime;
  }

  public Conversation text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Message text.
   * @return text
  **/
  @ApiModelProperty(example = "This is a sample message", required = true, value = "Message text.")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public Conversation receiver(String receiver) {
    this.receiver = receiver;
    return this;
  }

   /**
   * Receiver&#39;s phone number.
   * @return receiver
  **/
  @ApiModelProperty(example = "447624800500", required = true, value = "Receiver's phone number.")
  public String getReceiver() {
    return receiver;
  }

  public void setReceiver(String receiver) {
    this.receiver = receiver;
  }

  public Conversation status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Message status (for chats outbound only). See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details.
   * @return status
  **/
  @ApiModelProperty(example = "d", required = true, value = "Message status (for chats outbound only). See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Conversation firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Contact first name.
   * @return firstName
  **/
  @ApiModelProperty(example = "Charles", required = true, value = "Contact first name.")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public Conversation lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Contact last name.
   * @return lastName
  **/
  @ApiModelProperty(example = "Conway", required = true, value = "Contact last name.")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public Conversation sessionId(Integer sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Session ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.
   * @return sessionId
  **/
  @ApiModelProperty(required = true, value = "Session ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.")
  public Integer getSessionId() {
    return sessionId;
  }

  public void setSessionId(Integer sessionId) {
    this.sessionId = sessionId;
  }

  public Conversation initiatorId(Integer initiatorId) {
    this.initiatorId = initiatorId;
    return this;
  }

   /**
   * Initiator ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.
   * @return initiatorId
  **/
  @ApiModelProperty(value = "Initiator ID of a message. See [message sessions](https://docs.textmagic.com/#tag/Outbound-Message-Sessions) for details.")
  public Integer getInitiatorId() {
    return initiatorId;
  }

  public void setInitiatorId(Integer initiatorId) {
    this.initiatorId = initiatorId;
  }

  public Conversation messageFileId(Integer messageFileId) {
    this.messageFileId = messageFileId;
    return this;
  }

   /**
   * Message file id.
   * @return messageFileId
  **/
  @ApiModelProperty(value = "Message file id.")
  public Integer getMessageFileId() {
    return messageFileId;
  }

  public void setMessageFileId(Integer messageFileId) {
    this.messageFileId = messageFileId;
  }

  public Conversation type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Message type.
   * @return type
  **/
  @ApiModelProperty(example = "text", value = "Message type.")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public Conversation chatType(ChatTypeEnum chatType) {
    this.chatType = chatType;
    return this;
  }

   /**
   * Chat type.
   * @return chatType
  **/
  @ApiModelProperty(example = "text", value = "Chat type.")
  public ChatTypeEnum getChatType() {
    return chatType;
  }

  public void setChatType(ChatTypeEnum chatType) {
    this.chatType = chatType;
  }

  public Conversation chatId(Integer chatId) {
    this.chatId = chatId;
    return this;
  }

   /**
   * Chat id.
   * @return chatId
  **/
  @ApiModelProperty(value = "Chat id.")
  public Integer getChatId() {
    return chatId;
  }

  public void setChatId(Integer chatId) {
    this.chatId = chatId;
  }

  public Conversation isEdited(Boolean isEdited) {
    this.isEdited = isEdited;
    return this;
  }

   /**
   * Get isEdited
   * @return isEdited
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isIsEdited() {
    return isEdited;
  }

  public void setIsEdited(Boolean isEdited) {
    this.isEdited = isEdited;
  }

  public Conversation errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Error code.
   * @return errorCode
  **/
  @ApiModelProperty(example = "test_error_code", value = "Error code.")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public Conversation files(List<MessageFile> files) {
    this.files = files;
    return this;
  }

  public Conversation addFilesItem(MessageFile filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<MessageFile>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @ApiModelProperty(value = "")
  public List<MessageFile> getFiles() {
    return files;
  }

  public void setFiles(List<MessageFile> files) {
    this.files = files;
  }

  public Conversation payload(MessagePayload payload) {
    this.payload = payload;
    return this;
  }

   /**
   * Get payload
   * @return payload
  **/
  @ApiModelProperty(value = "")
  public MessagePayload getPayload() {
    return payload;
  }

  public void setPayload(MessagePayload payload) {
    this.payload = payload;
  }

  public Conversation avatar(String avatar) {
    this.avatar = avatar;
    return this;
  }

   /**
   * Get avatar
   * @return avatar
  **/
  @ApiModelProperty(example = "avatars/dummy_avatar.png", value = "")
  public String getAvatar() {
    return avatar;
  }

  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Conversation conversation = (Conversation) o;
    return Objects.equals(this.id, conversation.id) &&
        Objects.equals(this.direction, conversation.direction) &&
        Objects.equals(this.sender, conversation.sender) &&
        Objects.equals(this.messageTime, conversation.messageTime) &&
        Objects.equals(this.text, conversation.text) &&
        Objects.equals(this.receiver, conversation.receiver) &&
        Objects.equals(this.status, conversation.status) &&
        Objects.equals(this.firstName, conversation.firstName) &&
        Objects.equals(this.lastName, conversation.lastName) &&
        Objects.equals(this.sessionId, conversation.sessionId) &&
        Objects.equals(this.initiatorId, conversation.initiatorId) &&
        Objects.equals(this.messageFileId, conversation.messageFileId) &&
        Objects.equals(this.type, conversation.type) &&
        Objects.equals(this.chatType, conversation.chatType) &&
        Objects.equals(this.chatId, conversation.chatId) &&
        Objects.equals(this.isEdited, conversation.isEdited) &&
        Objects.equals(this.errorCode, conversation.errorCode) &&
        Objects.equals(this.files, conversation.files) &&
        Objects.equals(this.payload, conversation.payload) &&
        Objects.equals(this.avatar, conversation.avatar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, direction, sender, messageTime, text, receiver, status, firstName, lastName, sessionId, initiatorId, messageFileId, type, chatType, chatId, isEdited, errorCode, files, payload, avatar);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Conversation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    messageTime: ").append(toIndentedString(messageTime)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    receiver: ").append(toIndentedString(receiver)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    initiatorId: ").append(toIndentedString(initiatorId)).append("\n");
    sb.append("    messageFileId: ").append(toIndentedString(messageFileId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    chatType: ").append(toIndentedString(chatType)).append("\n");
    sb.append("    chatId: ").append(toIndentedString(chatId)).append("\n");
    sb.append("    isEdited: ").append(toIndentedString(isEdited)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

