/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.textmagic.sdk.model.Apiv2emailcampaignsRecipients;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateEmailCampaignInputObject
 */

public class CreateEmailCampaignInputObject {
  @SerializedName("emailSenderId")
  private Integer emailSenderId = null;

  @SerializedName("subject")
  private String subject = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("fromName")
  private String fromName = null;

  @SerializedName("replyToEmail")
  private String replyToEmail = null;

  @SerializedName("recipients")
  private Apiv2emailcampaignsRecipients recipients = null;

  public CreateEmailCampaignInputObject emailSenderId(Integer emailSenderId) {
    this.emailSenderId = emailSenderId;
    return this;
  }

   /**
   * Email sender ID from your configured senders.
   * @return emailSenderId
  **/
  @ApiModelProperty(example = "123", value = "Email sender ID from your configured senders.")
  public Integer getEmailSenderId() {
    return emailSenderId;
  }

  public void setEmailSenderId(Integer emailSenderId) {
    this.emailSenderId = emailSenderId;
  }

  public CreateEmailCampaignInputObject subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Email subject line.
   * @return subject
  **/
  @ApiModelProperty(example = "Special Offer - 50% Off Today Only!", value = "Email subject line.")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public CreateEmailCampaignInputObject message(String message) {
    this.message = message;
    return this;
  }

   /**
   * HTML email content.
   * @return message
  **/
  @ApiModelProperty(example = "<html><body><h1>Special Offer!</h1><p>Get 50% off all products today only!</p></body></html>", value = "HTML email content.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public CreateEmailCampaignInputObject fromName(String fromName) {
    this.fromName = fromName;
    return this;
  }

   /**
   * Optional custom sender name.
   * @return fromName
  **/
  @ApiModelProperty(example = "John Smith", value = "Optional custom sender name.")
  public String getFromName() {
    return fromName;
  }

  public void setFromName(String fromName) {
    this.fromName = fromName;
  }

  public CreateEmailCampaignInputObject replyToEmail(String replyToEmail) {
    this.replyToEmail = replyToEmail;
    return this;
  }

   /**
   * Optional custom reply-to email address.
   * @return replyToEmail
  **/
  @ApiModelProperty(example = "support@example.com", value = "Optional custom reply-to email address.")
  public String getReplyToEmail() {
    return replyToEmail;
  }

  public void setReplyToEmail(String replyToEmail) {
    this.replyToEmail = replyToEmail;
  }

  public CreateEmailCampaignInputObject recipients(Apiv2emailcampaignsRecipients recipients) {
    this.recipients = recipients;
    return this;
  }

   /**
   * Get recipients
   * @return recipients
  **/
  @ApiModelProperty(value = "")
  public Apiv2emailcampaignsRecipients getRecipients() {
    return recipients;
  }

  public void setRecipients(Apiv2emailcampaignsRecipients recipients) {
    this.recipients = recipients;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateEmailCampaignInputObject createEmailCampaignInputObject = (CreateEmailCampaignInputObject) o;
    return Objects.equals(this.emailSenderId, createEmailCampaignInputObject.emailSenderId) &&
        Objects.equals(this.subject, createEmailCampaignInputObject.subject) &&
        Objects.equals(this.message, createEmailCampaignInputObject.message) &&
        Objects.equals(this.fromName, createEmailCampaignInputObject.fromName) &&
        Objects.equals(this.replyToEmail, createEmailCampaignInputObject.replyToEmail) &&
        Objects.equals(this.recipients, createEmailCampaignInputObject.recipients);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailSenderId, subject, message, fromName, replyToEmail, recipients);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateEmailCampaignInputObject {\n");
    
    sb.append("    emailSenderId: ").append(toIndentedString(emailSenderId)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    fromName: ").append(toIndentedString(fromName)).append("\n");
    sb.append("    replyToEmail: ").append(toIndentedString(replyToEmail)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

