/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.textmagic.sdk.model.DoAuthResponseMinVersions;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * DoAuthResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class DoAuthResponse {
  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  @javax.annotation.Nonnull
  private String username;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  @javax.annotation.Nonnull
  private String token;

  public static final String SERIALIZED_NAME_EXPIRES = "expires";
  @SerializedName(SERIALIZED_NAME_EXPIRES)
  @javax.annotation.Nullable
  private OffsetDateTime expires;

  public static final String SERIALIZED_NAME_MIN_VERSIONS = "minVersions";
  @SerializedName(SERIALIZED_NAME_MIN_VERSIONS)
  @javax.annotation.Nonnull
  private DoAuthResponseMinVersions minVersions;

  public static final String SERIALIZED_NAME_DISALLOWED_RULES = "disallowedRules";
  @SerializedName(SERIALIZED_NAME_DISALLOWED_RULES)
  @javax.annotation.Nonnull
  private List<String> disallowedRules = new ArrayList<>();

  public DoAuthResponse() {
  }

  public DoAuthResponse username(@javax.annotation.Nonnull String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @javax.annotation.Nonnull
  public String getUsername() {
    return username;
  }

  public void setUsername(@javax.annotation.Nonnull String username) {
    this.username = username;
  }


  public DoAuthResponse token(@javax.annotation.Nonnull String token) {
    this.token = token;
    return this;
  }

  /**
   * Get token
   * @return token
   */
  @javax.annotation.Nonnull
  public String getToken() {
    return token;
  }

  public void setToken(@javax.annotation.Nonnull String token) {
    this.token = token;
  }


  public DoAuthResponse expires(@javax.annotation.Nullable OffsetDateTime expires) {
    this.expires = expires;
    return this;
  }

  /**
   * Get expires
   * @return expires
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpires() {
    return expires;
  }

  public void setExpires(@javax.annotation.Nullable OffsetDateTime expires) {
    this.expires = expires;
  }


  public DoAuthResponse minVersions(@javax.annotation.Nonnull DoAuthResponseMinVersions minVersions) {
    this.minVersions = minVersions;
    return this;
  }

  /**
   * Get minVersions
   * @return minVersions
   */
  @javax.annotation.Nonnull
  public DoAuthResponseMinVersions getMinVersions() {
    return minVersions;
  }

  public void setMinVersions(@javax.annotation.Nonnull DoAuthResponseMinVersions minVersions) {
    this.minVersions = minVersions;
  }


  public DoAuthResponse disallowedRules(@javax.annotation.Nonnull List<String> disallowedRules) {
    this.disallowedRules = disallowedRules;
    return this;
  }

  public DoAuthResponse addDisallowedRulesItem(String disallowedRulesItem) {
    if (this.disallowedRules == null) {
      this.disallowedRules = new ArrayList<>();
    }
    this.disallowedRules.add(disallowedRulesItem);
    return this;
  }

  /**
   * Get disallowedRules
   * @return disallowedRules
   */
  @javax.annotation.Nonnull
  public List<String> getDisallowedRules() {
    return disallowedRules;
  }

  public void setDisallowedRules(@javax.annotation.Nonnull List<String> disallowedRules) {
    this.disallowedRules = disallowedRules;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoAuthResponse doAuthResponse = (DoAuthResponse) o;
    return Objects.equals(this.username, doAuthResponse.username) &&
        Objects.equals(this.token, doAuthResponse.token) &&
        Objects.equals(this.expires, doAuthResponse.expires) &&
        Objects.equals(this.minVersions, doAuthResponse.minVersions) &&
        Objects.equals(this.disallowedRules, doAuthResponse.disallowedRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(username, token, expires, minVersions, disallowedRules);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoAuthResponse {\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    minVersions: ").append(toIndentedString(minVersions)).append("\n");
    sb.append("    disallowedRules: ").append(toIndentedString(disallowedRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("username", "token", "expires", "minVersions", "disallowedRules"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("username", "token", "expires", "minVersions", "disallowedRules"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DoAuthResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DoAuthResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in DoAuthResponse is not found in the empty JSON string", DoAuthResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DoAuthResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DoAuthResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DoAuthResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("username").toString()));
      }
      if (!jsonObj.get("token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token").toString()));
      }
      // validate the required field `minVersions`
      DoAuthResponseMinVersions.validateJsonElement(jsonObj.get("minVersions"));
      // ensure the required json array is present
      if (jsonObj.get("disallowedRules") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("disallowedRules").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `disallowedRules` to be an array in the JSON string but got `%s`", jsonObj.get("disallowedRules").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DoAuthResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DoAuthResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DoAuthResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DoAuthResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<DoAuthResponse>() {
           @Override
           public void write(JsonWriter out, DoAuthResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DoAuthResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DoAuthResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DoAuthResponse
   * @throws IOException if the JSON string is invalid with respect to DoAuthResponse
   */
  public static DoAuthResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DoAuthResponse.class);
  }

  /**
   * Convert an instance of DoAuthResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

