/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * EmailSenderItem
 */

public class EmailSenderItem {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("domainId")
  private Integer domainId = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("createdAt")
  private OffsetDateTime createdAt = null;

  /**
   * Current verification status of the associated domain.
   */
  @JsonAdapter(DomainStatusEnum.Adapter.class)
  public enum DomainStatusEnum {
    NOT_VERIFIED("not_verified"),
    
    PENDING("pending"),
    
    MANUAL_REVIEW("manual_review"),
    
    REJECTED("rejected"),
    
    VERIFIED("verified");

    private String value;

    DomainStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DomainStatusEnum fromValue(String text) {
      for (DomainStatusEnum b : DomainStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DomainStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DomainStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DomainStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DomainStatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("domainStatus")
  private DomainStatusEnum domainStatus = null;

  @SerializedName("fromName")
  private String fromName = null;

  @SerializedName("replyTo")
  private String replyTo = null;

  public EmailSenderItem id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Unique email sender identifier.
   * @return id
  **/
  @ApiModelProperty(example = "456", required = true, value = "Unique email sender identifier.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public EmailSenderItem domainId(Integer domainId) {
    this.domainId = domainId;
    return this;
  }

   /**
   * ID of the associated domain.
   * @return domainId
  **/
  @ApiModelProperty(example = "123", required = true, value = "ID of the associated domain.")
  public Integer getDomainId() {
    return domainId;
  }

  public void setDomainId(Integer domainId) {
    this.domainId = domainId;
  }

  public EmailSenderItem email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Email address of the sender.
   * @return email
  **/
  @ApiModelProperty(example = "noreply@company.com", required = true, value = "Email address of the sender.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public EmailSenderItem createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * When the email sender was created.
   * @return createdAt
  **/
  @ApiModelProperty(example = "2023-12-01T10:00:00Z", required = true, value = "When the email sender was created.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public EmailSenderItem domainStatus(DomainStatusEnum domainStatus) {
    this.domainStatus = domainStatus;
    return this;
  }

   /**
   * Current verification status of the associated domain.
   * @return domainStatus
  **/
  @ApiModelProperty(example = "verified", required = true, value = "Current verification status of the associated domain.")
  public DomainStatusEnum getDomainStatus() {
    return domainStatus;
  }

  public void setDomainStatus(DomainStatusEnum domainStatus) {
    this.domainStatus = domainStatus;
  }

  public EmailSenderItem fromName(String fromName) {
    this.fromName = fromName;
    return this;
  }

   /**
   * Display name for the sender.
   * @return fromName
  **/
  @ApiModelProperty(example = "Company Newsletter", value = "Display name for the sender.")
  public String getFromName() {
    return fromName;
  }

  public void setFromName(String fromName) {
    this.fromName = fromName;
  }

  public EmailSenderItem replyTo(String replyTo) {
    this.replyTo = replyTo;
    return this;
  }

   /**
   * Reply-to email address.
   * @return replyTo
  **/
  @ApiModelProperty(example = "support@company.com", value = "Reply-to email address.")
  public String getReplyTo() {
    return replyTo;
  }

  public void setReplyTo(String replyTo) {
    this.replyTo = replyTo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailSenderItem emailSenderItem = (EmailSenderItem) o;
    return Objects.equals(this.id, emailSenderItem.id) &&
        Objects.equals(this.domainId, emailSenderItem.domainId) &&
        Objects.equals(this.email, emailSenderItem.email) &&
        Objects.equals(this.createdAt, emailSenderItem.createdAt) &&
        Objects.equals(this.domainStatus, emailSenderItem.domainStatus) &&
        Objects.equals(this.fromName, emailSenderItem.fromName) &&
        Objects.equals(this.replyTo, emailSenderItem.replyTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, domainId, email, createdAt, domainStatus, fromName, replyTo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailSenderItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    domainId: ").append(toIndentedString(domainId)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    domainStatus: ").append(toIndentedString(domainStatus)).append("\n");
    sb.append("    fromName: ").append(toIndentedString(fromName)).append("\n");
    sb.append("    replyTo: ").append(toIndentedString(replyTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

