/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * GetAvailableSenderSettingOptionsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GetAvailableSenderSettingOptionsResponse {
  public static final String SERIALIZED_NAME_DEDICATED = "dedicated";
  @SerializedName(SERIALIZED_NAME_DEDICATED)
  @javax.annotation.Nonnull
  private List<String> dedicated = new ArrayList<>();

  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  @javax.annotation.Nonnull
  private List<String> user = new ArrayList<>();

  public static final String SERIALIZED_NAME_SHARED = "shared";
  @SerializedName(SERIALIZED_NAME_SHARED)
  @javax.annotation.Nonnull
  private List<String> shared = new ArrayList<>();

  public static final String SERIALIZED_NAME_SENDER_IDS = "senderIds";
  @SerializedName(SERIALIZED_NAME_SENDER_IDS)
  @javax.annotation.Nonnull
  private List<String> senderIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_USER_CARRIER_TWILIO = "userCarrierTwilio";
  @SerializedName(SERIALIZED_NAME_USER_CARRIER_TWILIO)
  @javax.annotation.Nonnull
  private List<String> userCarrierTwilio = new ArrayList<>();

  public static final String SERIALIZED_NAME_USER_CARRIER_VONAGE = "userCarrierVonage";
  @SerializedName(SERIALIZED_NAME_USER_CARRIER_VONAGE)
  @javax.annotation.Nonnull
  private List<String> userCarrierVonage = new ArrayList<>();

  public static final String SERIALIZED_NAME_USER_CARRIER_SINCH = "userCarrierSinch";
  @SerializedName(SERIALIZED_NAME_USER_CARRIER_SINCH)
  @javax.annotation.Nonnull
  private List<String> userCarrierSinch = new ArrayList<>();

  public static final String SERIALIZED_NAME_U_CARRIER_BANDWIDTH = "uCarrierBandwidth";
  @SerializedName(SERIALIZED_NAME_U_CARRIER_BANDWIDTH)
  @javax.annotation.Nullable
  private List<String> uCarrierBandwidth = new ArrayList<>();

  public static final String SERIALIZED_NAME_UC_TWILIO_SENDER_ID = "ucTwilioSenderId";
  @SerializedName(SERIALIZED_NAME_UC_TWILIO_SENDER_ID)
  @javax.annotation.Nullable
  private List<String> ucTwilioSenderId = new ArrayList<>();

  public GetAvailableSenderSettingOptionsResponse() {
  }

  public GetAvailableSenderSettingOptionsResponse dedicated(@javax.annotation.Nonnull List<String> dedicated) {
    this.dedicated = dedicated;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addDedicatedItem(String dedicatedItem) {
    if (this.dedicated == null) {
      this.dedicated = new ArrayList<>();
    }
    this.dedicated.add(dedicatedItem);
    return this;
  }

  /**
   * Array of dedicated number strings.
   * @return dedicated
   */
  @javax.annotation.Nonnull
  public List<String> getDedicated() {
    return dedicated;
  }

  public void setDedicated(@javax.annotation.Nonnull List<String> dedicated) {
    this.dedicated = dedicated;
  }


  public GetAvailableSenderSettingOptionsResponse user(@javax.annotation.Nonnull List<String> user) {
    this.user = user;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUserItem(String userItem) {
    if (this.user == null) {
      this.user = new ArrayList<>();
    }
    this.user.add(userItem);
    return this;
  }

  /**
   * Array of verified account phone numbers (currently only one).
   * @return user
   */
  @javax.annotation.Nonnull
  public List<String> getUser() {
    return user;
  }

  public void setUser(@javax.annotation.Nonnull List<String> user) {
    this.user = user;
  }


  public GetAvailableSenderSettingOptionsResponse shared(@javax.annotation.Nonnull List<String> shared) {
    this.shared = shared;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addSharedItem(String sharedItem) {
    if (this.shared == null) {
      this.shared = new ArrayList<>();
    }
    this.shared.add(sharedItem);
    return this;
  }

  /**
   * Array of shared number strings.
   * @return shared
   */
  @javax.annotation.Nonnull
  public List<String> getShared() {
    return shared;
  }

  public void setShared(@javax.annotation.Nonnull List<String> shared) {
    this.shared = shared;
  }


  public GetAvailableSenderSettingOptionsResponse senderIds(@javax.annotation.Nonnull List<String> senderIds) {
    this.senderIds = senderIds;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addSenderIdsItem(String senderIdsItem) {
    if (this.senderIds == null) {
      this.senderIds = new ArrayList<>();
    }
    this.senderIds.add(senderIdsItem);
    return this;
  }

  /**
   * Array of alphanumeric sender IDs.
   * @return senderIds
   */
  @javax.annotation.Nonnull
  public List<String> getSenderIds() {
    return senderIds;
  }

  public void setSenderIds(@javax.annotation.Nonnull List<String> senderIds) {
    this.senderIds = senderIds;
  }


  public GetAvailableSenderSettingOptionsResponse userCarrierTwilio(@javax.annotation.Nonnull List<String> userCarrierTwilio) {
    this.userCarrierTwilio = userCarrierTwilio;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUserCarrierTwilioItem(String userCarrierTwilioItem) {
    if (this.userCarrierTwilio == null) {
      this.userCarrierTwilio = new ArrayList<>();
    }
    this.userCarrierTwilio.add(userCarrierTwilioItem);
    return this;
  }

  /**
   * Array of alphanumeric sender IDs.
   * @return userCarrierTwilio
   */
  @javax.annotation.Nonnull
  public List<String> getUserCarrierTwilio() {
    return userCarrierTwilio;
  }

  public void setUserCarrierTwilio(@javax.annotation.Nonnull List<String> userCarrierTwilio) {
    this.userCarrierTwilio = userCarrierTwilio;
  }


  public GetAvailableSenderSettingOptionsResponse userCarrierVonage(@javax.annotation.Nonnull List<String> userCarrierVonage) {
    this.userCarrierVonage = userCarrierVonage;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUserCarrierVonageItem(String userCarrierVonageItem) {
    if (this.userCarrierVonage == null) {
      this.userCarrierVonage = new ArrayList<>();
    }
    this.userCarrierVonage.add(userCarrierVonageItem);
    return this;
  }

  /**
   * Array of alphanumeric sender IDs.
   * @return userCarrierVonage
   */
  @javax.annotation.Nonnull
  public List<String> getUserCarrierVonage() {
    return userCarrierVonage;
  }

  public void setUserCarrierVonage(@javax.annotation.Nonnull List<String> userCarrierVonage) {
    this.userCarrierVonage = userCarrierVonage;
  }


  public GetAvailableSenderSettingOptionsResponse userCarrierSinch(@javax.annotation.Nonnull List<String> userCarrierSinch) {
    this.userCarrierSinch = userCarrierSinch;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUserCarrierSinchItem(String userCarrierSinchItem) {
    if (this.userCarrierSinch == null) {
      this.userCarrierSinch = new ArrayList<>();
    }
    this.userCarrierSinch.add(userCarrierSinchItem);
    return this;
  }

  /**
   * Array of alphanumeric sender IDs.
   * @return userCarrierSinch
   */
  @javax.annotation.Nonnull
  public List<String> getUserCarrierSinch() {
    return userCarrierSinch;
  }

  public void setUserCarrierSinch(@javax.annotation.Nonnull List<String> userCarrierSinch) {
    this.userCarrierSinch = userCarrierSinch;
  }


  public GetAvailableSenderSettingOptionsResponse uCarrierBandwidth(@javax.annotation.Nullable List<String> uCarrierBandwidth) {
    this.uCarrierBandwidth = uCarrierBandwidth;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUCarrierBandwidthItem(String uCarrierBandwidthItem) {
    if (this.uCarrierBandwidth == null) {
      this.uCarrierBandwidth = new ArrayList<>();
    }
    this.uCarrierBandwidth.add(uCarrierBandwidthItem);
    return this;
  }

  /**
   * Array of alphanumeric sender IDs.
   * @return uCarrierBandwidth
   */
  @javax.annotation.Nullable
  public List<String> getuCarrierBandwidth() {
    return uCarrierBandwidth;
  }

  public void setuCarrierBandwidth(@javax.annotation.Nullable List<String> uCarrierBandwidth) {
    this.uCarrierBandwidth = uCarrierBandwidth;
  }


  public GetAvailableSenderSettingOptionsResponse ucTwilioSenderId(@javax.annotation.Nullable List<String> ucTwilioSenderId) {
    this.ucTwilioSenderId = ucTwilioSenderId;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUcTwilioSenderIdItem(String ucTwilioSenderIdItem) {
    if (this.ucTwilioSenderId == null) {
      this.ucTwilioSenderId = new ArrayList<>();
    }
    this.ucTwilioSenderId.add(ucTwilioSenderIdItem);
    return this;
  }

  /**
   * Array of alphanumeric sender IDs.
   * @return ucTwilioSenderId
   */
  @javax.annotation.Nullable
  public List<String> getUcTwilioSenderId() {
    return ucTwilioSenderId;
  }

  public void setUcTwilioSenderId(@javax.annotation.Nullable List<String> ucTwilioSenderId) {
    this.ucTwilioSenderId = ucTwilioSenderId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAvailableSenderSettingOptionsResponse getAvailableSenderSettingOptionsResponse = (GetAvailableSenderSettingOptionsResponse) o;
    return Objects.equals(this.dedicated, getAvailableSenderSettingOptionsResponse.dedicated) &&
        Objects.equals(this.user, getAvailableSenderSettingOptionsResponse.user) &&
        Objects.equals(this.shared, getAvailableSenderSettingOptionsResponse.shared) &&
        Objects.equals(this.senderIds, getAvailableSenderSettingOptionsResponse.senderIds) &&
        Objects.equals(this.userCarrierTwilio, getAvailableSenderSettingOptionsResponse.userCarrierTwilio) &&
        Objects.equals(this.userCarrierVonage, getAvailableSenderSettingOptionsResponse.userCarrierVonage) &&
        Objects.equals(this.userCarrierSinch, getAvailableSenderSettingOptionsResponse.userCarrierSinch) &&
        Objects.equals(this.uCarrierBandwidth, getAvailableSenderSettingOptionsResponse.uCarrierBandwidth) &&
        Objects.equals(this.ucTwilioSenderId, getAvailableSenderSettingOptionsResponse.ucTwilioSenderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dedicated, user, shared, senderIds, userCarrierTwilio, userCarrierVonage, userCarrierSinch, uCarrierBandwidth, ucTwilioSenderId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAvailableSenderSettingOptionsResponse {\n");
    sb.append("    dedicated: ").append(toIndentedString(dedicated)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    shared: ").append(toIndentedString(shared)).append("\n");
    sb.append("    senderIds: ").append(toIndentedString(senderIds)).append("\n");
    sb.append("    userCarrierTwilio: ").append(toIndentedString(userCarrierTwilio)).append("\n");
    sb.append("    userCarrierVonage: ").append(toIndentedString(userCarrierVonage)).append("\n");
    sb.append("    userCarrierSinch: ").append(toIndentedString(userCarrierSinch)).append("\n");
    sb.append("    uCarrierBandwidth: ").append(toIndentedString(uCarrierBandwidth)).append("\n");
    sb.append("    ucTwilioSenderId: ").append(toIndentedString(ucTwilioSenderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("dedicated", "user", "shared", "senderIds", "userCarrierTwilio", "userCarrierVonage", "userCarrierSinch", "uCarrierBandwidth", "ucTwilioSenderId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("dedicated", "user", "shared", "senderIds", "userCarrierTwilio", "userCarrierVonage", "userCarrierSinch"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetAvailableSenderSettingOptionsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetAvailableSenderSettingOptionsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetAvailableSenderSettingOptionsResponse is not found in the empty JSON string", GetAvailableSenderSettingOptionsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetAvailableSenderSettingOptionsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetAvailableSenderSettingOptionsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetAvailableSenderSettingOptionsResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("dedicated") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("dedicated").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `dedicated` to be an array in the JSON string but got `%s`", jsonObj.get("dedicated").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("user") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("user").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `user` to be an array in the JSON string but got `%s`", jsonObj.get("user").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("shared") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("shared").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `shared` to be an array in the JSON string but got `%s`", jsonObj.get("shared").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("senderIds") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("senderIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `senderIds` to be an array in the JSON string but got `%s`", jsonObj.get("senderIds").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("userCarrierTwilio") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("userCarrierTwilio").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `userCarrierTwilio` to be an array in the JSON string but got `%s`", jsonObj.get("userCarrierTwilio").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("userCarrierVonage") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("userCarrierVonage").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `userCarrierVonage` to be an array in the JSON string but got `%s`", jsonObj.get("userCarrierVonage").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("userCarrierSinch") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("userCarrierSinch").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `userCarrierSinch` to be an array in the JSON string but got `%s`", jsonObj.get("userCarrierSinch").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("uCarrierBandwidth") != null && !jsonObj.get("uCarrierBandwidth").isJsonNull() && !jsonObj.get("uCarrierBandwidth").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `uCarrierBandwidth` to be an array in the JSON string but got `%s`", jsonObj.get("uCarrierBandwidth").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("ucTwilioSenderId") != null && !jsonObj.get("ucTwilioSenderId").isJsonNull() && !jsonObj.get("ucTwilioSenderId").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `ucTwilioSenderId` to be an array in the JSON string but got `%s`", jsonObj.get("ucTwilioSenderId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetAvailableSenderSettingOptionsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetAvailableSenderSettingOptionsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetAvailableSenderSettingOptionsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetAvailableSenderSettingOptionsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetAvailableSenderSettingOptionsResponse>() {
           @Override
           public void write(JsonWriter out, GetAvailableSenderSettingOptionsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetAvailableSenderSettingOptionsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetAvailableSenderSettingOptionsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetAvailableSenderSettingOptionsResponse
   * @throws IOException if the JSON string is invalid with respect to GetAvailableSenderSettingOptionsResponse
   */
  public static GetAvailableSenderSettingOptionsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetAvailableSenderSettingOptionsResponse.class);
  }

  /**
   * Convert an instance of GetAvailableSenderSettingOptionsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

