/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GetAvailableSenderSettingOptionsResponse
 */

public class GetAvailableSenderSettingOptionsResponse {
  @SerializedName("dedicated")
  private List<String> dedicated = new ArrayList<String>();

  @SerializedName("user")
  private List<String> user = new ArrayList<String>();

  @SerializedName("shared")
  private List<String> shared = new ArrayList<String>();

  @SerializedName("senderIds")
  private List<String> senderIds = new ArrayList<String>();

  @SerializedName("userCarrierTwilio")
  private List<String> userCarrierTwilio = new ArrayList<String>();

  @SerializedName("userCarrierVonage")
  private List<String> userCarrierVonage = new ArrayList<String>();

  @SerializedName("userCarrierSinch")
  private List<String> userCarrierSinch = new ArrayList<String>();

  @SerializedName("uCarrierBandwidth")
  private List<String> uCarrierBandwidth = null;

  @SerializedName("ucTwilioSenderId")
  private List<String> ucTwilioSenderId = null;

  public GetAvailableSenderSettingOptionsResponse dedicated(List<String> dedicated) {
    this.dedicated = dedicated;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addDedicatedItem(String dedicatedItem) {
    this.dedicated.add(dedicatedItem);
    return this;
  }

   /**
   * Array of dedicated number strings.
   * @return dedicated
  **/
  @ApiModelProperty(example = "[447860021136,447860021137]", required = true, value = "Array of dedicated number strings.")
  public List<String> getDedicated() {
    return dedicated;
  }

  public void setDedicated(List<String> dedicated) {
    this.dedicated = dedicated;
  }

  public GetAvailableSenderSettingOptionsResponse user(List<String> user) {
    this.user = user;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUserItem(String userItem) {
    this.user.add(userItem);
    return this;
  }

   /**
   * Array of verified account phone numbers (currently only one).
   * @return user
  **/
  @ApiModelProperty(example = "[447860021134,447860021135]", required = true, value = "Array of verified account phone numbers (currently only one).")
  public List<String> getUser() {
    return user;
  }

  public void setUser(List<String> user) {
    this.user = user;
  }

  public GetAvailableSenderSettingOptionsResponse shared(List<String> shared) {
    this.shared = shared;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addSharedItem(String sharedItem) {
    this.shared.add(sharedItem);
    return this;
  }

   /**
   * Array of shared number strings.
   * @return shared
  **/
  @ApiModelProperty(example = "[447860021130,447860021131]", required = true, value = "Array of shared number strings.")
  public List<String> getShared() {
    return shared;
  }

  public void setShared(List<String> shared) {
    this.shared = shared;
  }

  public GetAvailableSenderSettingOptionsResponse senderIds(List<String> senderIds) {
    this.senderIds = senderIds;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addSenderIdsItem(String senderIdsItem) {
    this.senderIds.add(senderIdsItem);
    return this;
  }

   /**
   * Array of alphanumeric sender IDs.
   * @return senderIds
  **/
  @ApiModelProperty(example = "[447860021132,447860021133]", required = true, value = "Array of alphanumeric sender IDs.")
  public List<String> getSenderIds() {
    return senderIds;
  }

  public void setSenderIds(List<String> senderIds) {
    this.senderIds = senderIds;
  }

  public GetAvailableSenderSettingOptionsResponse userCarrierTwilio(List<String> userCarrierTwilio) {
    this.userCarrierTwilio = userCarrierTwilio;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUserCarrierTwilioItem(String userCarrierTwilioItem) {
    this.userCarrierTwilio.add(userCarrierTwilioItem);
    return this;
  }

   /**
   * Array of alphanumeric sender IDs.
   * @return userCarrierTwilio
  **/
  @ApiModelProperty(example = "[447860021136,447860021137]", required = true, value = "Array of alphanumeric sender IDs.")
  public List<String> getUserCarrierTwilio() {
    return userCarrierTwilio;
  }

  public void setUserCarrierTwilio(List<String> userCarrierTwilio) {
    this.userCarrierTwilio = userCarrierTwilio;
  }

  public GetAvailableSenderSettingOptionsResponse userCarrierVonage(List<String> userCarrierVonage) {
    this.userCarrierVonage = userCarrierVonage;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUserCarrierVonageItem(String userCarrierVonageItem) {
    this.userCarrierVonage.add(userCarrierVonageItem);
    return this;
  }

   /**
   * Array of alphanumeric sender IDs.
   * @return userCarrierVonage
  **/
  @ApiModelProperty(example = "[447860021138,447860021139]", required = true, value = "Array of alphanumeric sender IDs.")
  public List<String> getUserCarrierVonage() {
    return userCarrierVonage;
  }

  public void setUserCarrierVonage(List<String> userCarrierVonage) {
    this.userCarrierVonage = userCarrierVonage;
  }

  public GetAvailableSenderSettingOptionsResponse userCarrierSinch(List<String> userCarrierSinch) {
    this.userCarrierSinch = userCarrierSinch;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUserCarrierSinchItem(String userCarrierSinchItem) {
    this.userCarrierSinch.add(userCarrierSinchItem);
    return this;
  }

   /**
   * Array of alphanumeric sender IDs.
   * @return userCarrierSinch
  **/
  @ApiModelProperty(example = "[447860021140,447860021141]", required = true, value = "Array of alphanumeric sender IDs.")
  public List<String> getUserCarrierSinch() {
    return userCarrierSinch;
  }

  public void setUserCarrierSinch(List<String> userCarrierSinch) {
    this.userCarrierSinch = userCarrierSinch;
  }

  public GetAvailableSenderSettingOptionsResponse uCarrierBandwidth(List<String> uCarrierBandwidth) {
    this.uCarrierBandwidth = uCarrierBandwidth;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUCarrierBandwidthItem(String uCarrierBandwidthItem) {
    if (this.uCarrierBandwidth == null) {
      this.uCarrierBandwidth = new ArrayList<String>();
    }
    this.uCarrierBandwidth.add(uCarrierBandwidthItem);
    return this;
  }

   /**
   * Array of alphanumeric sender IDs.
   * @return uCarrierBandwidth
  **/
  @ApiModelProperty(example = "[447860021142,447860021143]", value = "Array of alphanumeric sender IDs.")
  public List<String> getUCarrierBandwidth() {
    return uCarrierBandwidth;
  }

  public void setUCarrierBandwidth(List<String> uCarrierBandwidth) {
    this.uCarrierBandwidth = uCarrierBandwidth;
  }

  public GetAvailableSenderSettingOptionsResponse ucTwilioSenderId(List<String> ucTwilioSenderId) {
    this.ucTwilioSenderId = ucTwilioSenderId;
    return this;
  }

  public GetAvailableSenderSettingOptionsResponse addUcTwilioSenderIdItem(String ucTwilioSenderIdItem) {
    if (this.ucTwilioSenderId == null) {
      this.ucTwilioSenderId = new ArrayList<String>();
    }
    this.ucTwilioSenderId.add(ucTwilioSenderIdItem);
    return this;
  }

   /**
   * Array of alphanumeric sender IDs.
   * @return ucTwilioSenderId
  **/
  @ApiModelProperty(example = "[\"TestSender1\",\"TestSender2\"]", value = "Array of alphanumeric sender IDs.")
  public List<String> getUcTwilioSenderId() {
    return ucTwilioSenderId;
  }

  public void setUcTwilioSenderId(List<String> ucTwilioSenderId) {
    this.ucTwilioSenderId = ucTwilioSenderId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAvailableSenderSettingOptionsResponse getAvailableSenderSettingOptionsResponse = (GetAvailableSenderSettingOptionsResponse) o;
    return Objects.equals(this.dedicated, getAvailableSenderSettingOptionsResponse.dedicated) &&
        Objects.equals(this.user, getAvailableSenderSettingOptionsResponse.user) &&
        Objects.equals(this.shared, getAvailableSenderSettingOptionsResponse.shared) &&
        Objects.equals(this.senderIds, getAvailableSenderSettingOptionsResponse.senderIds) &&
        Objects.equals(this.userCarrierTwilio, getAvailableSenderSettingOptionsResponse.userCarrierTwilio) &&
        Objects.equals(this.userCarrierVonage, getAvailableSenderSettingOptionsResponse.userCarrierVonage) &&
        Objects.equals(this.userCarrierSinch, getAvailableSenderSettingOptionsResponse.userCarrierSinch) &&
        Objects.equals(this.uCarrierBandwidth, getAvailableSenderSettingOptionsResponse.uCarrierBandwidth) &&
        Objects.equals(this.ucTwilioSenderId, getAvailableSenderSettingOptionsResponse.ucTwilioSenderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dedicated, user, shared, senderIds, userCarrierTwilio, userCarrierVonage, userCarrierSinch, uCarrierBandwidth, ucTwilioSenderId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAvailableSenderSettingOptionsResponse {\n");
    
    sb.append("    dedicated: ").append(toIndentedString(dedicated)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    shared: ").append(toIndentedString(shared)).append("\n");
    sb.append("    senderIds: ").append(toIndentedString(senderIds)).append("\n");
    sb.append("    userCarrierTwilio: ").append(toIndentedString(userCarrierTwilio)).append("\n");
    sb.append("    userCarrierVonage: ").append(toIndentedString(userCarrierVonage)).append("\n");
    sb.append("    userCarrierSinch: ").append(toIndentedString(userCarrierSinch)).append("\n");
    sb.append("    uCarrierBandwidth: ").append(toIndentedString(uCarrierBandwidth)).append("\n");
    sb.append("    ucTwilioSenderId: ").append(toIndentedString(ucTwilioSenderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

