/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * GetBalanceNotificationOptionsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GetBalanceNotificationOptionsResponse {
  public static final String SERIALIZED_NAME_1 = "1";
  @SerializedName(SERIALIZED_NAME_1)
  @javax.annotation.Nonnull
  private String _1;

  public static final String SERIALIZED_NAME_2 = "2";
  @SerializedName(SERIALIZED_NAME_2)
  @javax.annotation.Nonnull
  private String _2;

  public static final String SERIALIZED_NAME_3 = "3";
  @SerializedName(SERIALIZED_NAME_3)
  @javax.annotation.Nonnull
  private String _3;

  public static final String SERIALIZED_NAME_5 = "5";
  @SerializedName(SERIALIZED_NAME_5)
  @javax.annotation.Nonnull
  private String _5;

  public static final String SERIALIZED_NAME_10 = "10";
  @SerializedName(SERIALIZED_NAME_10)
  @javax.annotation.Nonnull
  private String _10;

  public static final String SERIALIZED_NAME_20 = "20";
  @SerializedName(SERIALIZED_NAME_20)
  @javax.annotation.Nonnull
  private String _20;

  public static final String SERIALIZED_NAME_30 = "30";
  @SerializedName(SERIALIZED_NAME_30)
  @javax.annotation.Nonnull
  private String _30;

  public static final String SERIALIZED_NAME_50 = "50";
  @SerializedName(SERIALIZED_NAME_50)
  @javax.annotation.Nonnull
  private String _50;

  public static final String SERIALIZED_NAME_100 = "100";
  @SerializedName(SERIALIZED_NAME_100)
  @javax.annotation.Nonnull
  private String _100;

  public static final String SERIALIZED_NAME_500 = "500";
  @SerializedName(SERIALIZED_NAME_500)
  @javax.annotation.Nonnull
  private String _500;

  public static final String SERIALIZED_NAME_1000 = "1000";
  @SerializedName(SERIALIZED_NAME_1000)
  @javax.annotation.Nonnull
  private String _1000;

  public GetBalanceNotificationOptionsResponse() {
  }

  public GetBalanceNotificationOptionsResponse _1(@javax.annotation.Nonnull String _1) {
    this._1 = _1;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _1
   */
  @javax.annotation.Nonnull
  public String get1() {
    return _1;
  }

  public void set1(@javax.annotation.Nonnull String _1) {
    this._1 = _1;
  }


  public GetBalanceNotificationOptionsResponse _2(@javax.annotation.Nonnull String _2) {
    this._2 = _2;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _2
   */
  @javax.annotation.Nonnull
  public String get2() {
    return _2;
  }

  public void set2(@javax.annotation.Nonnull String _2) {
    this._2 = _2;
  }


  public GetBalanceNotificationOptionsResponse _3(@javax.annotation.Nonnull String _3) {
    this._3 = _3;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _3
   */
  @javax.annotation.Nonnull
  public String get3() {
    return _3;
  }

  public void set3(@javax.annotation.Nonnull String _3) {
    this._3 = _3;
  }


  public GetBalanceNotificationOptionsResponse _5(@javax.annotation.Nonnull String _5) {
    this._5 = _5;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _5
   */
  @javax.annotation.Nonnull
  public String get5() {
    return _5;
  }

  public void set5(@javax.annotation.Nonnull String _5) {
    this._5 = _5;
  }


  public GetBalanceNotificationOptionsResponse _10(@javax.annotation.Nonnull String _10) {
    this._10 = _10;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _10
   */
  @javax.annotation.Nonnull
  public String get10() {
    return _10;
  }

  public void set10(@javax.annotation.Nonnull String _10) {
    this._10 = _10;
  }


  public GetBalanceNotificationOptionsResponse _20(@javax.annotation.Nonnull String _20) {
    this._20 = _20;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _20
   */
  @javax.annotation.Nonnull
  public String get20() {
    return _20;
  }

  public void set20(@javax.annotation.Nonnull String _20) {
    this._20 = _20;
  }


  public GetBalanceNotificationOptionsResponse _30(@javax.annotation.Nonnull String _30) {
    this._30 = _30;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _30
   */
  @javax.annotation.Nonnull
  public String get30() {
    return _30;
  }

  public void set30(@javax.annotation.Nonnull String _30) {
    this._30 = _30;
  }


  public GetBalanceNotificationOptionsResponse _50(@javax.annotation.Nonnull String _50) {
    this._50 = _50;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _50
   */
  @javax.annotation.Nonnull
  public String get50() {
    return _50;
  }

  public void set50(@javax.annotation.Nonnull String _50) {
    this._50 = _50;
  }


  public GetBalanceNotificationOptionsResponse _100(@javax.annotation.Nonnull String _100) {
    this._100 = _100;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _100
   */
  @javax.annotation.Nonnull
  public String get100() {
    return _100;
  }

  public void set100(@javax.annotation.Nonnull String _100) {
    this._100 = _100;
  }


  public GetBalanceNotificationOptionsResponse _500(@javax.annotation.Nonnull String _500) {
    this._500 = _500;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _500
   */
  @javax.annotation.Nonnull
  public String get500() {
    return _500;
  }

  public void set500(@javax.annotation.Nonnull String _500) {
    this._500 = _500;
  }


  public GetBalanceNotificationOptionsResponse _1000(@javax.annotation.Nonnull String _1000) {
    this._1000 = _1000;
    return this;
  }

  /**
   * Contains sign of currency in Unicode hex code.
   * @return _1000
   */
  @javax.annotation.Nonnull
  public String get1000() {
    return _1000;
  }

  public void set1000(@javax.annotation.Nonnull String _1000) {
    this._1000 = _1000;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBalanceNotificationOptionsResponse getBalanceNotificationOptionsResponse = (GetBalanceNotificationOptionsResponse) o;
    return Objects.equals(this._1, getBalanceNotificationOptionsResponse._1) &&
        Objects.equals(this._2, getBalanceNotificationOptionsResponse._2) &&
        Objects.equals(this._3, getBalanceNotificationOptionsResponse._3) &&
        Objects.equals(this._5, getBalanceNotificationOptionsResponse._5) &&
        Objects.equals(this._10, getBalanceNotificationOptionsResponse._10) &&
        Objects.equals(this._20, getBalanceNotificationOptionsResponse._20) &&
        Objects.equals(this._30, getBalanceNotificationOptionsResponse._30) &&
        Objects.equals(this._50, getBalanceNotificationOptionsResponse._50) &&
        Objects.equals(this._100, getBalanceNotificationOptionsResponse._100) &&
        Objects.equals(this._500, getBalanceNotificationOptionsResponse._500) &&
        Objects.equals(this._1000, getBalanceNotificationOptionsResponse._1000);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_1, _2, _3, _5, _10, _20, _30, _50, _100, _500, _1000);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBalanceNotificationOptionsResponse {\n");
    sb.append("    _1: ").append(toIndentedString(_1)).append("\n");
    sb.append("    _2: ").append(toIndentedString(_2)).append("\n");
    sb.append("    _3: ").append(toIndentedString(_3)).append("\n");
    sb.append("    _5: ").append(toIndentedString(_5)).append("\n");
    sb.append("    _10: ").append(toIndentedString(_10)).append("\n");
    sb.append("    _20: ").append(toIndentedString(_20)).append("\n");
    sb.append("    _30: ").append(toIndentedString(_30)).append("\n");
    sb.append("    _50: ").append(toIndentedString(_50)).append("\n");
    sb.append("    _100: ").append(toIndentedString(_100)).append("\n");
    sb.append("    _500: ").append(toIndentedString(_500)).append("\n");
    sb.append("    _1000: ").append(toIndentedString(_1000)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("1", "2", "3", "5", "10", "20", "30", "50", "100", "500", "1000"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("1", "2", "3", "5", "10", "20", "30", "50", "100", "500", "1000"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetBalanceNotificationOptionsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetBalanceNotificationOptionsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetBalanceNotificationOptionsResponse is not found in the empty JSON string", GetBalanceNotificationOptionsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetBalanceNotificationOptionsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetBalanceNotificationOptionsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetBalanceNotificationOptionsResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("1").toString()));
      }
      if (!jsonObj.get("2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("2").toString()));
      }
      if (!jsonObj.get("3").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `3` to be a primitive type in the JSON string but got `%s`", jsonObj.get("3").toString()));
      }
      if (!jsonObj.get("5").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `5` to be a primitive type in the JSON string but got `%s`", jsonObj.get("5").toString()));
      }
      if (!jsonObj.get("10").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `10` to be a primitive type in the JSON string but got `%s`", jsonObj.get("10").toString()));
      }
      if (!jsonObj.get("20").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `20` to be a primitive type in the JSON string but got `%s`", jsonObj.get("20").toString()));
      }
      if (!jsonObj.get("30").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `30` to be a primitive type in the JSON string but got `%s`", jsonObj.get("30").toString()));
      }
      if (!jsonObj.get("50").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `50` to be a primitive type in the JSON string but got `%s`", jsonObj.get("50").toString()));
      }
      if (!jsonObj.get("100").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `100` to be a primitive type in the JSON string but got `%s`", jsonObj.get("100").toString()));
      }
      if (!jsonObj.get("500").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `500` to be a primitive type in the JSON string but got `%s`", jsonObj.get("500").toString()));
      }
      if (!jsonObj.get("1000").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `1000` to be a primitive type in the JSON string but got `%s`", jsonObj.get("1000").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetBalanceNotificationOptionsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetBalanceNotificationOptionsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetBalanceNotificationOptionsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetBalanceNotificationOptionsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetBalanceNotificationOptionsResponse>() {
           @Override
           public void write(JsonWriter out, GetBalanceNotificationOptionsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetBalanceNotificationOptionsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetBalanceNotificationOptionsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetBalanceNotificationOptionsResponse
   * @throws IOException if the JSON string is invalid with respect to GetBalanceNotificationOptionsResponse
   */
  public static GetBalanceNotificationOptionsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetBalanceNotificationOptionsResponse.class);
  }

  /**
   * Convert an instance of GetBalanceNotificationOptionsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

