/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * GetCallsPricesResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GetCallsPricesResponse {
  public static final String SERIALIZED_NAME_OUTBOUND = "outbound";
  @SerializedName(SERIALIZED_NAME_OUTBOUND)
  @javax.annotation.Nonnull
  private BigDecimal outbound;

  public static final String SERIALIZED_NAME_INBOUND = "inbound";
  @SerializedName(SERIALIZED_NAME_INBOUND)
  @javax.annotation.Nonnull
  private BigDecimal inbound;

  public static final String SERIALIZED_NAME_FORWARD = "forward";
  @SerializedName(SERIALIZED_NAME_FORWARD)
  @javax.annotation.Nonnull
  private BigDecimal forward;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nonnull
  private String country;

  public GetCallsPricesResponse() {
  }

  public GetCallsPricesResponse outbound(@javax.annotation.Nonnull BigDecimal outbound) {
    this.outbound = outbound;
    return this;
  }

  /**
   * Price for outbound message.
   * @return outbound
   */
  @javax.annotation.Nonnull
  public BigDecimal getOutbound() {
    return outbound;
  }

  public void setOutbound(@javax.annotation.Nonnull BigDecimal outbound) {
    this.outbound = outbound;
  }


  public GetCallsPricesResponse inbound(@javax.annotation.Nonnull BigDecimal inbound) {
    this.inbound = inbound;
    return this;
  }

  /**
   * Price for inbound message.
   * @return inbound
   */
  @javax.annotation.Nonnull
  public BigDecimal getInbound() {
    return inbound;
  }

  public void setInbound(@javax.annotation.Nonnull BigDecimal inbound) {
    this.inbound = inbound;
  }


  public GetCallsPricesResponse forward(@javax.annotation.Nonnull BigDecimal forward) {
    this.forward = forward;
    return this;
  }

  /**
   * Price for forward.
   * @return forward
   */
  @javax.annotation.Nonnull
  public BigDecimal getForward() {
    return forward;
  }

  public void setForward(@javax.annotation.Nonnull BigDecimal forward) {
    this.forward = forward;
  }


  public GetCallsPricesResponse country(@javax.annotation.Nonnull String country) {
    this.country = country;
    return this;
  }

  /**
   * 2-letter ISO country code for local phone numbers, used when local is  set to true. Default is account country.
   * @return country
   */
  @javax.annotation.Nonnull
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nonnull String country) {
    this.country = country;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCallsPricesResponse getCallsPricesResponse = (GetCallsPricesResponse) o;
    return Objects.equals(this.outbound, getCallsPricesResponse.outbound) &&
        Objects.equals(this.inbound, getCallsPricesResponse.inbound) &&
        Objects.equals(this.forward, getCallsPricesResponse.forward) &&
        Objects.equals(this.country, getCallsPricesResponse.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outbound, inbound, forward, country);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCallsPricesResponse {\n");
    sb.append("    outbound: ").append(toIndentedString(outbound)).append("\n");
    sb.append("    inbound: ").append(toIndentedString(inbound)).append("\n");
    sb.append("    forward: ").append(toIndentedString(forward)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("outbound", "inbound", "forward", "country"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("outbound", "inbound", "forward", "country"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetCallsPricesResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetCallsPricesResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetCallsPricesResponse is not found in the empty JSON string", GetCallsPricesResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetCallsPricesResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetCallsPricesResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetCallsPricesResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetCallsPricesResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetCallsPricesResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetCallsPricesResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetCallsPricesResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetCallsPricesResponse>() {
           @Override
           public void write(JsonWriter out, GetCallsPricesResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetCallsPricesResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetCallsPricesResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetCallsPricesResponse
   * @throws IOException if the JSON string is invalid with respect to GetCallsPricesResponse
   */
  public static GetCallsPricesResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetCallsPricesResponse.class);
  }

  /**
   * Convert an instance of GetCallsPricesResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

