/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * GetMessageSessionStatResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GetMessageSessionStatResponse {
  public static final String SERIALIZED_NAME_FAILED = "failed";
  @SerializedName(SERIALIZED_NAME_FAILED)
  @javax.annotation.Nonnull
  private Integer failed;

  public static final String SERIALIZED_NAME_DELIVERED = "delivered";
  @SerializedName(SERIALIZED_NAME_DELIVERED)
  @javax.annotation.Nonnull
  private Integer delivered;

  public static final String SERIALIZED_NAME_ACCEPTED = "accepted";
  @SerializedName(SERIALIZED_NAME_ACCEPTED)
  @javax.annotation.Nonnull
  private Integer accepted;

  public static final String SERIALIZED_NAME_REJECTED = "rejected";
  @SerializedName(SERIALIZED_NAME_REJECTED)
  @javax.annotation.Nonnull
  private Integer rejected;

  public static final String SERIALIZED_NAME_SCHEDULED = "scheduled";
  @SerializedName(SERIALIZED_NAME_SCHEDULED)
  @javax.annotation.Nonnull
  private Integer scheduled;

  public static final String SERIALIZED_NAME_ALL = "all";
  @SerializedName(SERIALIZED_NAME_ALL)
  @javax.annotation.Nonnull
  private Integer all;

  public static final String SERIALIZED_NAME_SENT = "sent";
  @SerializedName(SERIALIZED_NAME_SENT)
  @javax.annotation.Nonnull
  private Integer sent;

  public GetMessageSessionStatResponse() {
  }

  public GetMessageSessionStatResponse failed(@javax.annotation.Nonnull Integer failed) {
    this.failed = failed;
    return this;
  }

  /**
   * Amount of failed messages.
   * @return failed
   */
  @javax.annotation.Nonnull
  public Integer getFailed() {
    return failed;
  }

  public void setFailed(@javax.annotation.Nonnull Integer failed) {
    this.failed = failed;
  }


  public GetMessageSessionStatResponse delivered(@javax.annotation.Nonnull Integer delivered) {
    this.delivered = delivered;
    return this;
  }

  /**
   * Amount of delivered messages.
   * @return delivered
   */
  @javax.annotation.Nonnull
  public Integer getDelivered() {
    return delivered;
  }

  public void setDelivered(@javax.annotation.Nonnull Integer delivered) {
    this.delivered = delivered;
  }


  public GetMessageSessionStatResponse accepted(@javax.annotation.Nonnull Integer accepted) {
    this.accepted = accepted;
    return this;
  }

  /**
   * Amount of accepted messages.
   * @return accepted
   */
  @javax.annotation.Nonnull
  public Integer getAccepted() {
    return accepted;
  }

  public void setAccepted(@javax.annotation.Nonnull Integer accepted) {
    this.accepted = accepted;
  }


  public GetMessageSessionStatResponse rejected(@javax.annotation.Nonnull Integer rejected) {
    this.rejected = rejected;
    return this;
  }

  /**
   * Amount of rejected messages.
   * @return rejected
   */
  @javax.annotation.Nonnull
  public Integer getRejected() {
    return rejected;
  }

  public void setRejected(@javax.annotation.Nonnull Integer rejected) {
    this.rejected = rejected;
  }


  public GetMessageSessionStatResponse scheduled(@javax.annotation.Nonnull Integer scheduled) {
    this.scheduled = scheduled;
    return this;
  }

  /**
   * Amount of scheduled messages.
   * @return scheduled
   */
  @javax.annotation.Nonnull
  public Integer getScheduled() {
    return scheduled;
  }

  public void setScheduled(@javax.annotation.Nonnull Integer scheduled) {
    this.scheduled = scheduled;
  }


  public GetMessageSessionStatResponse all(@javax.annotation.Nonnull Integer all) {
    this.all = all;
    return this;
  }

  /**
   * Total amount of messages.
   * @return all
   */
  @javax.annotation.Nonnull
  public Integer getAll() {
    return all;
  }

  public void setAll(@javax.annotation.Nonnull Integer all) {
    this.all = all;
  }


  public GetMessageSessionStatResponse sent(@javax.annotation.Nonnull Integer sent) {
    this.sent = sent;
    return this;
  }

  /**
   * Amount of sent but not yet delivered messages.
   * @return sent
   */
  @javax.annotation.Nonnull
  public Integer getSent() {
    return sent;
  }

  public void setSent(@javax.annotation.Nonnull Integer sent) {
    this.sent = sent;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMessageSessionStatResponse getMessageSessionStatResponse = (GetMessageSessionStatResponse) o;
    return Objects.equals(this.failed, getMessageSessionStatResponse.failed) &&
        Objects.equals(this.delivered, getMessageSessionStatResponse.delivered) &&
        Objects.equals(this.accepted, getMessageSessionStatResponse.accepted) &&
        Objects.equals(this.rejected, getMessageSessionStatResponse.rejected) &&
        Objects.equals(this.scheduled, getMessageSessionStatResponse.scheduled) &&
        Objects.equals(this.all, getMessageSessionStatResponse.all) &&
        Objects.equals(this.sent, getMessageSessionStatResponse.sent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failed, delivered, accepted, rejected, scheduled, all, sent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMessageSessionStatResponse {\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    delivered: ").append(toIndentedString(delivered)).append("\n");
    sb.append("    accepted: ").append(toIndentedString(accepted)).append("\n");
    sb.append("    rejected: ").append(toIndentedString(rejected)).append("\n");
    sb.append("    scheduled: ").append(toIndentedString(scheduled)).append("\n");
    sb.append("    all: ").append(toIndentedString(all)).append("\n");
    sb.append("    sent: ").append(toIndentedString(sent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("failed", "delivered", "accepted", "rejected", "scheduled", "all", "sent"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("failed", "delivered", "accepted", "rejected", "scheduled", "all", "sent"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetMessageSessionStatResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetMessageSessionStatResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in GetMessageSessionStatResponse is not found in the empty JSON string", GetMessageSessionStatResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetMessageSessionStatResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetMessageSessionStatResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetMessageSessionStatResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetMessageSessionStatResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetMessageSessionStatResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetMessageSessionStatResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetMessageSessionStatResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetMessageSessionStatResponse>() {
           @Override
           public void write(JsonWriter out, GetMessageSessionStatResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetMessageSessionStatResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetMessageSessionStatResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetMessageSessionStatResponse
   * @throws IOException if the JSON string is invalid with respect to GetMessageSessionStatResponse
   */
  public static GetMessageSessionStatResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetMessageSessionStatResponse.class);
  }

  /**
   * Convert an instance of GetMessageSessionStatResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

