/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * MessagesIcsParametersRecipients
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class MessagesIcsParametersRecipients {
  public static final String SERIALIZED_NAME_CONTACTS = "contacts";
  @SerializedName(SERIALIZED_NAME_CONTACTS)
  @javax.annotation.Nonnull
  private List<Integer> contacts = new ArrayList<>();

  public static final String SERIALIZED_NAME_GROUPS = "groups";
  @SerializedName(SERIALIZED_NAME_GROUPS)
  @javax.annotation.Nonnull
  private List<Integer> groups = new ArrayList<>();

  public static final String SERIALIZED_NAME_NUMBERS = "numbers";
  @SerializedName(SERIALIZED_NAME_NUMBERS)
  @javax.annotation.Nonnull
  private List<String> numbers = new ArrayList<>();

  public static final String SERIALIZED_NAME_FILTERED_VIEWS = "filteredViews";
  @SerializedName(SERIALIZED_NAME_FILTERED_VIEWS)
  @javax.annotation.Nonnull
  private List<Integer> filteredViews = new ArrayList<>();

  public MessagesIcsParametersRecipients() {
  }

  public MessagesIcsParametersRecipients contacts(@javax.annotation.Nonnull List<Integer> contacts) {
    this.contacts = contacts;
    return this;
  }

  public MessagesIcsParametersRecipients addContactsItem(Integer contactsItem) {
    if (this.contacts == null) {
      this.contacts = new ArrayList<>();
    }
    this.contacts.add(contactsItem);
    return this;
  }

  /**
   * Get contacts
   * @return contacts
   */
  @javax.annotation.Nonnull
  public List<Integer> getContacts() {
    return contacts;
  }

  public void setContacts(@javax.annotation.Nonnull List<Integer> contacts) {
    this.contacts = contacts;
  }


  public MessagesIcsParametersRecipients groups(@javax.annotation.Nonnull List<Integer> groups) {
    this.groups = groups;
    return this;
  }

  public MessagesIcsParametersRecipients addGroupsItem(Integer groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

  /**
   * Get groups
   * @return groups
   */
  @javax.annotation.Nonnull
  public List<Integer> getGroups() {
    return groups;
  }

  public void setGroups(@javax.annotation.Nonnull List<Integer> groups) {
    this.groups = groups;
  }


  public MessagesIcsParametersRecipients numbers(@javax.annotation.Nonnull List<String> numbers) {
    this.numbers = numbers;
    return this;
  }

  public MessagesIcsParametersRecipients addNumbersItem(String numbersItem) {
    if (this.numbers == null) {
      this.numbers = new ArrayList<>();
    }
    this.numbers.add(numbersItem);
    return this;
  }

  /**
   * Get numbers
   * @return numbers
   */
  @javax.annotation.Nonnull
  public List<String> getNumbers() {
    return numbers;
  }

  public void setNumbers(@javax.annotation.Nonnull List<String> numbers) {
    this.numbers = numbers;
  }


  public MessagesIcsParametersRecipients filteredViews(@javax.annotation.Nonnull List<Integer> filteredViews) {
    this.filteredViews = filteredViews;
    return this;
  }

  public MessagesIcsParametersRecipients addFilteredViewsItem(Integer filteredViewsItem) {
    if (this.filteredViews == null) {
      this.filteredViews = new ArrayList<>();
    }
    this.filteredViews.add(filteredViewsItem);
    return this;
  }

  /**
   * Get filteredViews
   * @return filteredViews
   */
  @javax.annotation.Nonnull
  public List<Integer> getFilteredViews() {
    return filteredViews;
  }

  public void setFilteredViews(@javax.annotation.Nonnull List<Integer> filteredViews) {
    this.filteredViews = filteredViews;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessagesIcsParametersRecipients messagesIcsParametersRecipients = (MessagesIcsParametersRecipients) o;
    return Objects.equals(this.contacts, messagesIcsParametersRecipients.contacts) &&
        Objects.equals(this.groups, messagesIcsParametersRecipients.groups) &&
        Objects.equals(this.numbers, messagesIcsParametersRecipients.numbers) &&
        Objects.equals(this.filteredViews, messagesIcsParametersRecipients.filteredViews);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contacts, groups, numbers, filteredViews);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessagesIcsParametersRecipients {\n");
    sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    numbers: ").append(toIndentedString(numbers)).append("\n");
    sb.append("    filteredViews: ").append(toIndentedString(filteredViews)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("contacts", "groups", "numbers", "filteredViews"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("contacts", "groups", "numbers", "filteredViews"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MessagesIcsParametersRecipients
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MessagesIcsParametersRecipients.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in MessagesIcsParametersRecipients is not found in the empty JSON string", MessagesIcsParametersRecipients.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MessagesIcsParametersRecipients.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MessagesIcsParametersRecipients` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MessagesIcsParametersRecipients.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("contacts") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("contacts").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `contacts` to be an array in the JSON string but got `%s`", jsonObj.get("contacts").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("groups") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("groups").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `groups` to be an array in the JSON string but got `%s`", jsonObj.get("groups").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("numbers") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("numbers").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `numbers` to be an array in the JSON string but got `%s`", jsonObj.get("numbers").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("filteredViews") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("filteredViews").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `filteredViews` to be an array in the JSON string but got `%s`", jsonObj.get("filteredViews").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MessagesIcsParametersRecipients.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MessagesIcsParametersRecipients' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MessagesIcsParametersRecipients> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MessagesIcsParametersRecipients.class));

       return (TypeAdapter<T>) new TypeAdapter<MessagesIcsParametersRecipients>() {
           @Override
           public void write(JsonWriter out, MessagesIcsParametersRecipients value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MessagesIcsParametersRecipients read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MessagesIcsParametersRecipients given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MessagesIcsParametersRecipients
   * @throws IOException if the JSON string is invalid with respect to MessagesIcsParametersRecipients
   */
  public static MessagesIcsParametersRecipients fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MessagesIcsParametersRecipients.class);
  }

  /**
   * Convert an instance of MessagesIcsParametersRecipients to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

