/*
 * Textmagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.textmagic.sdk.model.ScheduledEmailCampaignDetails;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ScheduleEmailCampaignResponse
 */

public class ScheduleEmailCampaignResponse {
  @SerializedName("campaign")
  private ScheduledEmailCampaignDetails campaign = null;

  @SerializedName("cost")
  private Float cost = null;

  public ScheduleEmailCampaignResponse campaign(ScheduledEmailCampaignDetails campaign) {
    this.campaign = campaign;
    return this;
  }

   /**
   * Get campaign
   * @return campaign
  **/
  @ApiModelProperty(required = true, value = "")
  public ScheduledEmailCampaignDetails getCampaign() {
    return campaign;
  }

  public void setCampaign(ScheduledEmailCampaignDetails campaign) {
    this.campaign = campaign;
  }

  public ScheduleEmailCampaignResponse cost(Float cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Estimated cost for sending this campaign.
   * @return cost
  **/
  @ApiModelProperty(example = "12.5", required = true, value = "Estimated cost for sending this campaign.")
  public Float getCost() {
    return cost;
  }

  public void setCost(Float cost) {
    this.cost = cost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleEmailCampaignResponse scheduleEmailCampaignResponse = (ScheduleEmailCampaignResponse) o;
    return Objects.equals(this.campaign, scheduleEmailCampaignResponse.campaign) &&
        Objects.equals(this.cost, scheduleEmailCampaignResponse.cost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campaign, cost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleEmailCampaignResponse {\n");
    
    sb.append("    campaign: ").append(toIndentedString(campaign)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

