/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.textmagic.sdk.model.UserPersonalInfo;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * ScheduledEmailCampaignDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ScheduledEmailCampaignDetails {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Integer id;

  /**
   * Current scheduled campaign status.
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    SCHEDULED("scheduled"),
    
    ACTIVE("active"),
    
    PAUSED("paused"),
    
    COMPLETED("completed"),
    
    CANCELLED("cancelled"),
    
    FAILED("failed");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private StatusEnum status;

  public static final String SERIALIZED_NAME_EMAIL_SENDER_ID = "emailSenderId";
  @SerializedName(SERIALIZED_NAME_EMAIL_SENDER_ID)
  @javax.annotation.Nullable
  private Integer emailSenderId;

  public static final String SERIALIZED_NAME_START_AT = "startAt";
  @SerializedName(SERIALIZED_NAME_START_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime startAt;

  public static final String SERIALIZED_NAME_END_AT = "endAt";
  @SerializedName(SERIALIZED_NAME_END_AT)
  @javax.annotation.Nullable
  private OffsetDateTime endAt;

  public static final String SERIALIZED_NAME_NEXT_SEND_AT = "nextSendAt";
  @SerializedName(SERIALIZED_NAME_NEXT_SEND_AT)
  @javax.annotation.Nullable
  private OffsetDateTime nextSendAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  @javax.annotation.Nonnull
  private UserPersonalInfo createdBy;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  /**
   * Campaign recurrence type.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    ONCE("once"),
    
    HOURLY("hourly"),
    
    DAILY("daily"),
    
    WEEKLY("weekly"),
    
    MONTHLY("monthly"),
    
    YEARLY("yearly"),
    
    FOLLOW_UP("follow-up");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String SERIALIZED_NAME_FROM_NAME = "fromName";
  @SerializedName(SERIALIZED_NAME_FROM_NAME)
  @javax.annotation.Nullable
  private String fromName;

  public static final String SERIALIZED_NAME_FROM_EMAIL = "fromEmail";
  @SerializedName(SERIALIZED_NAME_FROM_EMAIL)
  @javax.annotation.Nonnull
  private String fromEmail;

  public static final String SERIALIZED_NAME_REPLY_TO_EMAIL = "replyToEmail";
  @SerializedName(SERIALIZED_NAME_REPLY_TO_EMAIL)
  @javax.annotation.Nonnull
  private String replyToEmail;

  public static final String SERIALIZED_NAME_SUBJECT = "subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  @javax.annotation.Nonnull
  private String subject;

  public static final String SERIALIZED_NAME_HTML = "html";
  @SerializedName(SERIALIZED_NAME_HTML)
  @javax.annotation.Nonnull
  private String html;

  public static final String SERIALIZED_NAME_RECIPIENTS_COUNT = "recipientsCount";
  @SerializedName(SERIALIZED_NAME_RECIPIENTS_COUNT)
  @javax.annotation.Nonnull
  private Integer recipientsCount;

  public static final String SERIALIZED_NAME_SENDING_TIMEZONE = "sendingTimezone";
  @SerializedName(SERIALIZED_NAME_SENDING_TIMEZONE)
  @javax.annotation.Nonnull
  private String sendingTimezone;

  public static final String SERIALIZED_NAME_RRULE = "rrule";
  @SerializedName(SERIALIZED_NAME_RRULE)
  @javax.annotation.Nullable
  private String rrule;

  public static final String SERIALIZED_NAME_OCCURRENCE_SUMMARY = "occurrenceSummary";
  @SerializedName(SERIALIZED_NAME_OCCURRENCE_SUMMARY)
  @javax.annotation.Nullable
  private String occurrenceSummary;

  public ScheduledEmailCampaignDetails() {
  }

  public ScheduledEmailCampaignDetails id(@javax.annotation.Nonnull Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Unique scheduled campaign ID.
   * @return id
   */
  @javax.annotation.Nonnull
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull Integer id) {
    this.id = id;
  }


  public ScheduledEmailCampaignDetails status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Current scheduled campaign status.
   * @return status
   */
  @javax.annotation.Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public ScheduledEmailCampaignDetails emailSenderId(@javax.annotation.Nullable Integer emailSenderId) {
    this.emailSenderId = emailSenderId;
    return this;
  }

  /**
   * Email sender ID used for this campaign.
   * @return emailSenderId
   */
  @javax.annotation.Nullable
  public Integer getEmailSenderId() {
    return emailSenderId;
  }

  public void setEmailSenderId(@javax.annotation.Nullable Integer emailSenderId) {
    this.emailSenderId = emailSenderId;
  }


  public ScheduledEmailCampaignDetails startAt(@javax.annotation.Nonnull OffsetDateTime startAt) {
    this.startAt = startAt;
    return this;
  }

  /**
   * Scheduled start timestamp (UTC).
   * @return startAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getStartAt() {
    return startAt;
  }

  public void setStartAt(@javax.annotation.Nonnull OffsetDateTime startAt) {
    this.startAt = startAt;
  }


  public ScheduledEmailCampaignDetails endAt(@javax.annotation.Nullable OffsetDateTime endAt) {
    this.endAt = endAt;
    return this;
  }

  /**
   * End timestamp for recurring campaigns (UTC).
   * @return endAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getEndAt() {
    return endAt;
  }

  public void setEndAt(@javax.annotation.Nullable OffsetDateTime endAt) {
    this.endAt = endAt;
  }


  public ScheduledEmailCampaignDetails nextSendAt(@javax.annotation.Nullable OffsetDateTime nextSendAt) {
    this.nextSendAt = nextSendAt;
    return this;
  }

  /**
   * Next scheduled send timestamp (UTC).
   * @return nextSendAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getNextSendAt() {
    return nextSendAt;
  }

  public void setNextSendAt(@javax.annotation.Nullable OffsetDateTime nextSendAt) {
    this.nextSendAt = nextSendAt;
  }


  public ScheduledEmailCampaignDetails createdBy(@javax.annotation.Nonnull UserPersonalInfo createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nonnull
  public UserPersonalInfo getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(@javax.annotation.Nonnull UserPersonalInfo createdBy) {
    this.createdBy = createdBy;
  }


  public ScheduledEmailCampaignDetails createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Campaign creation timestamp.
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ScheduledEmailCampaignDetails updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Last update timestamp.
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ScheduledEmailCampaignDetails type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Campaign recurrence type.
   * @return type
   */
  @javax.annotation.Nonnull
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public ScheduledEmailCampaignDetails fromName(@javax.annotation.Nullable String fromName) {
    this.fromName = fromName;
    return this;
  }

  /**
   * Sender name displayed in recipient&#39;s inbox.
   * @return fromName
   */
  @javax.annotation.Nullable
  public String getFromName() {
    return fromName;
  }

  public void setFromName(@javax.annotation.Nullable String fromName) {
    this.fromName = fromName;
  }


  public ScheduledEmailCampaignDetails fromEmail(@javax.annotation.Nonnull String fromEmail) {
    this.fromEmail = fromEmail;
    return this;
  }

  /**
   * Sender email address.
   * @return fromEmail
   */
  @javax.annotation.Nonnull
  public String getFromEmail() {
    return fromEmail;
  }

  public void setFromEmail(@javax.annotation.Nonnull String fromEmail) {
    this.fromEmail = fromEmail;
  }


  public ScheduledEmailCampaignDetails replyToEmail(@javax.annotation.Nonnull String replyToEmail) {
    this.replyToEmail = replyToEmail;
    return this;
  }

  /**
   * Reply-to email address.
   * @return replyToEmail
   */
  @javax.annotation.Nonnull
  public String getReplyToEmail() {
    return replyToEmail;
  }

  public void setReplyToEmail(@javax.annotation.Nonnull String replyToEmail) {
    this.replyToEmail = replyToEmail;
  }


  public ScheduledEmailCampaignDetails subject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Email subject line.
   * @return subject
   */
  @javax.annotation.Nonnull
  public String getSubject() {
    return subject;
  }

  public void setSubject(@javax.annotation.Nonnull String subject) {
    this.subject = subject;
  }


  public ScheduledEmailCampaignDetails html(@javax.annotation.Nonnull String html) {
    this.html = html;
    return this;
  }

  /**
   * HTML email content.
   * @return html
   */
  @javax.annotation.Nonnull
  public String getHtml() {
    return html;
  }

  public void setHtml(@javax.annotation.Nonnull String html) {
    this.html = html;
  }


  public ScheduledEmailCampaignDetails recipientsCount(@javax.annotation.Nonnull Integer recipientsCount) {
    this.recipientsCount = recipientsCount;
    return this;
  }

  /**
   * Number of recipients for this campaign.
   * @return recipientsCount
   */
  @javax.annotation.Nonnull
  public Integer getRecipientsCount() {
    return recipientsCount;
  }

  public void setRecipientsCount(@javax.annotation.Nonnull Integer recipientsCount) {
    this.recipientsCount = recipientsCount;
  }


  public ScheduledEmailCampaignDetails sendingTimezone(@javax.annotation.Nonnull String sendingTimezone) {
    this.sendingTimezone = sendingTimezone;
    return this;
  }

  /**
   * Timezone for sending the campaign.
   * @return sendingTimezone
   */
  @javax.annotation.Nonnull
  public String getSendingTimezone() {
    return sendingTimezone;
  }

  public void setSendingTimezone(@javax.annotation.Nonnull String sendingTimezone) {
    this.sendingTimezone = sendingTimezone;
  }


  public ScheduledEmailCampaignDetails rrule(@javax.annotation.Nullable String rrule) {
    this.rrule = rrule;
    return this;
  }

  /**
   * RFC 5545 recurrence rule for recurring campaigns.
   * @return rrule
   */
  @javax.annotation.Nullable
  public String getRrule() {
    return rrule;
  }

  public void setRrule(@javax.annotation.Nullable String rrule) {
    this.rrule = rrule;
  }


  public ScheduledEmailCampaignDetails occurrenceSummary(@javax.annotation.Nullable String occurrenceSummary) {
    this.occurrenceSummary = occurrenceSummary;
    return this;
  }

  /**
   * Human-readable schedule description.
   * @return occurrenceSummary
   */
  @javax.annotation.Nullable
  public String getOccurrenceSummary() {
    return occurrenceSummary;
  }

  public void setOccurrenceSummary(@javax.annotation.Nullable String occurrenceSummary) {
    this.occurrenceSummary = occurrenceSummary;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduledEmailCampaignDetails scheduledEmailCampaignDetails = (ScheduledEmailCampaignDetails) o;
    return Objects.equals(this.id, scheduledEmailCampaignDetails.id) &&
        Objects.equals(this.status, scheduledEmailCampaignDetails.status) &&
        Objects.equals(this.emailSenderId, scheduledEmailCampaignDetails.emailSenderId) &&
        Objects.equals(this.startAt, scheduledEmailCampaignDetails.startAt) &&
        Objects.equals(this.endAt, scheduledEmailCampaignDetails.endAt) &&
        Objects.equals(this.nextSendAt, scheduledEmailCampaignDetails.nextSendAt) &&
        Objects.equals(this.createdBy, scheduledEmailCampaignDetails.createdBy) &&
        Objects.equals(this.createdAt, scheduledEmailCampaignDetails.createdAt) &&
        Objects.equals(this.updatedAt, scheduledEmailCampaignDetails.updatedAt) &&
        Objects.equals(this.type, scheduledEmailCampaignDetails.type) &&
        Objects.equals(this.fromName, scheduledEmailCampaignDetails.fromName) &&
        Objects.equals(this.fromEmail, scheduledEmailCampaignDetails.fromEmail) &&
        Objects.equals(this.replyToEmail, scheduledEmailCampaignDetails.replyToEmail) &&
        Objects.equals(this.subject, scheduledEmailCampaignDetails.subject) &&
        Objects.equals(this.html, scheduledEmailCampaignDetails.html) &&
        Objects.equals(this.recipientsCount, scheduledEmailCampaignDetails.recipientsCount) &&
        Objects.equals(this.sendingTimezone, scheduledEmailCampaignDetails.sendingTimezone) &&
        Objects.equals(this.rrule, scheduledEmailCampaignDetails.rrule) &&
        Objects.equals(this.occurrenceSummary, scheduledEmailCampaignDetails.occurrenceSummary);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, emailSenderId, startAt, endAt, nextSendAt, createdBy, createdAt, updatedAt, type, fromName, fromEmail, replyToEmail, subject, html, recipientsCount, sendingTimezone, rrule, occurrenceSummary);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduledEmailCampaignDetails {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    emailSenderId: ").append(toIndentedString(emailSenderId)).append("\n");
    sb.append("    startAt: ").append(toIndentedString(startAt)).append("\n");
    sb.append("    endAt: ").append(toIndentedString(endAt)).append("\n");
    sb.append("    nextSendAt: ").append(toIndentedString(nextSendAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    fromName: ").append(toIndentedString(fromName)).append("\n");
    sb.append("    fromEmail: ").append(toIndentedString(fromEmail)).append("\n");
    sb.append("    replyToEmail: ").append(toIndentedString(replyToEmail)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    recipientsCount: ").append(toIndentedString(recipientsCount)).append("\n");
    sb.append("    sendingTimezone: ").append(toIndentedString(sendingTimezone)).append("\n");
    sb.append("    rrule: ").append(toIndentedString(rrule)).append("\n");
    sb.append("    occurrenceSummary: ").append(toIndentedString(occurrenceSummary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "status", "emailSenderId", "startAt", "endAt", "nextSendAt", "createdBy", "createdAt", "updatedAt", "type", "fromName", "fromEmail", "replyToEmail", "subject", "html", "recipientsCount", "sendingTimezone", "rrule", "occurrenceSummary"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "status", "startAt", "createdBy", "createdAt", "updatedAt", "type", "fromEmail", "replyToEmail", "subject", "html", "recipientsCount", "sendingTimezone"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScheduledEmailCampaignDetails
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScheduledEmailCampaignDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ScheduledEmailCampaignDetails is not found in the empty JSON string", ScheduledEmailCampaignDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ScheduledEmailCampaignDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ScheduledEmailCampaignDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ScheduledEmailCampaignDetails.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the required field `status`
      StatusEnum.validateJsonElement(jsonObj.get("status"));
      // validate the required field `createdBy`
      UserPersonalInfo.validateJsonElement(jsonObj.get("createdBy"));
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the required field `type`
      TypeEnum.validateJsonElement(jsonObj.get("type"));
      if ((jsonObj.get("fromName") != null && !jsonObj.get("fromName").isJsonNull()) && !jsonObj.get("fromName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `fromName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fromName").toString()));
      }
      if (!jsonObj.get("fromEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `fromEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fromEmail").toString()));
      }
      if (!jsonObj.get("replyToEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `replyToEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("replyToEmail").toString()));
      }
      if (!jsonObj.get("subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subject").toString()));
      }
      if (!jsonObj.get("html").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `html` to be a primitive type in the JSON string but got `%s`", jsonObj.get("html").toString()));
      }
      if (!jsonObj.get("sendingTimezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `sendingTimezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sendingTimezone").toString()));
      }
      if ((jsonObj.get("rrule") != null && !jsonObj.get("rrule").isJsonNull()) && !jsonObj.get("rrule").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `rrule` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rrule").toString()));
      }
      if ((jsonObj.get("occurrenceSummary") != null && !jsonObj.get("occurrenceSummary").isJsonNull()) && !jsonObj.get("occurrenceSummary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `occurrenceSummary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("occurrenceSummary").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScheduledEmailCampaignDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScheduledEmailCampaignDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScheduledEmailCampaignDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScheduledEmailCampaignDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<ScheduledEmailCampaignDetails>() {
           @Override
           public void write(JsonWriter out, ScheduledEmailCampaignDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScheduledEmailCampaignDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScheduledEmailCampaignDetails given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScheduledEmailCampaignDetails
   * @throws IOException if the JSON string is invalid with respect to ScheduledEmailCampaignDetails
   */
  public static ScheduledEmailCampaignDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScheduledEmailCampaignDetails.class);
  }

  /**
   * Convert an instance of ScheduledEmailCampaignDetails to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

