/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * Scheduling configuration for the campaign.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ScheduleEmailCampaignRequestScheduleParams {
  public static final String SERIALIZED_NAME_START_DATE_TIME = "startDateTime";
  @SerializedName(SERIALIZED_NAME_START_DATE_TIME)
  @javax.annotation.Nonnull
  private OffsetDateTime startDateTime;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nonnull
  private String timezone;

  public static final String SERIALIZED_NAME_RRULE = "rrule";
  @SerializedName(SERIALIZED_NAME_RRULE)
  @javax.annotation.Nullable
  private String rrule;

  public ScheduleEmailCampaignRequestScheduleParams() {
  }

  public ScheduleEmailCampaignRequestScheduleParams startDateTime(@javax.annotation.Nonnull OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
    return this;
  }

  /**
   * When to start sending the campaign (ISO 8601 format).
   * @return startDateTime
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getStartDateTime() {
    return startDateTime;
  }

  public void setStartDateTime(@javax.annotation.Nonnull OffsetDateTime startDateTime) {
    this.startDateTime = startDateTime;
  }


  public ScheduleEmailCampaignRequestScheduleParams timezone(@javax.annotation.Nonnull String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * Timezone for the schedule (e.g., \&quot;America/New_York\&quot;).
   * @return timezone
   */
  @javax.annotation.Nonnull
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nonnull String timezone) {
    this.timezone = timezone;
  }


  public ScheduleEmailCampaignRequestScheduleParams rrule(@javax.annotation.Nullable String rrule) {
    this.rrule = rrule;
    return this;
  }

  /**
   * RFC 5545 recurrence rule for recurring campaigns.
   * @return rrule
   */
  @javax.annotation.Nullable
  public String getRrule() {
    return rrule;
  }

  public void setRrule(@javax.annotation.Nullable String rrule) {
    this.rrule = rrule;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleEmailCampaignRequestScheduleParams scheduleEmailCampaignRequestScheduleParams = (ScheduleEmailCampaignRequestScheduleParams) o;
    return Objects.equals(this.startDateTime, scheduleEmailCampaignRequestScheduleParams.startDateTime) &&
        Objects.equals(this.timezone, scheduleEmailCampaignRequestScheduleParams.timezone) &&
        Objects.equals(this.rrule, scheduleEmailCampaignRequestScheduleParams.rrule);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(startDateTime, timezone, rrule);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleEmailCampaignRequestScheduleParams {\n");
    sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    rrule: ").append(toIndentedString(rrule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("startDateTime", "timezone", "rrule"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("startDateTime", "timezone"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScheduleEmailCampaignRequestScheduleParams
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScheduleEmailCampaignRequestScheduleParams.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ScheduleEmailCampaignRequestScheduleParams is not found in the empty JSON string", ScheduleEmailCampaignRequestScheduleParams.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ScheduleEmailCampaignRequestScheduleParams.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ScheduleEmailCampaignRequestScheduleParams` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ScheduleEmailCampaignRequestScheduleParams.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
      if ((jsonObj.get("rrule") != null && !jsonObj.get("rrule").isJsonNull()) && !jsonObj.get("rrule").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `rrule` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rrule").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScheduleEmailCampaignRequestScheduleParams.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScheduleEmailCampaignRequestScheduleParams' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScheduleEmailCampaignRequestScheduleParams> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScheduleEmailCampaignRequestScheduleParams.class));

       return (TypeAdapter<T>) new TypeAdapter<ScheduleEmailCampaignRequestScheduleParams>() {
           @Override
           public void write(JsonWriter out, ScheduleEmailCampaignRequestScheduleParams value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScheduleEmailCampaignRequestScheduleParams read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScheduleEmailCampaignRequestScheduleParams given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScheduleEmailCampaignRequestScheduleParams
   * @throws IOException if the JSON string is invalid with respect to ScheduleEmailCampaignRequestScheduleParams
   */
  public static ScheduleEmailCampaignRequestScheduleParams fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScheduleEmailCampaignRequestScheduleParams.class);
  }

  /**
   * Convert an instance of ScheduleEmailCampaignRequestScheduleParams to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

