/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * Campaign recipients configuration.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ScheduleEmailCampaignRequestRecipients {
  public static final String SERIALIZED_NAME_CONTACT_IDS = "contactIds";
  @SerializedName(SERIALIZED_NAME_CONTACT_IDS)
  @javax.annotation.Nonnull
  private List<Integer> contactIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_EMAILS = "emails";
  @SerializedName(SERIALIZED_NAME_EMAILS)
  @javax.annotation.Nonnull
  private List<String> emails = new ArrayList<>();

  public static final String SERIALIZED_NAME_GROUP_IDS = "groupIds";
  @SerializedName(SERIALIZED_NAME_GROUP_IDS)
  @javax.annotation.Nonnull
  private List<Integer> groupIds = new ArrayList<>();

  public ScheduleEmailCampaignRequestRecipients() {
  }

  public ScheduleEmailCampaignRequestRecipients contactIds(@javax.annotation.Nonnull List<Integer> contactIds) {
    this.contactIds = contactIds;
    return this;
  }

  public ScheduleEmailCampaignRequestRecipients addContactIdsItem(Integer contactIdsItem) {
    if (this.contactIds == null) {
      this.contactIds = new ArrayList<>();
    }
    this.contactIds.add(contactIdsItem);
    return this;
  }

  /**
   * Array of contact IDs to send to.
   * @return contactIds
   */
  @javax.annotation.Nonnull
  public List<Integer> getContactIds() {
    return contactIds;
  }

  public void setContactIds(@javax.annotation.Nonnull List<Integer> contactIds) {
    this.contactIds = contactIds;
  }


  public ScheduleEmailCampaignRequestRecipients emails(@javax.annotation.Nonnull List<String> emails) {
    this.emails = emails;
    return this;
  }

  public ScheduleEmailCampaignRequestRecipients addEmailsItem(String emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<>();
    }
    this.emails.add(emailsItem);
    return this;
  }

  /**
   * Array of email addresses to send to.
   * @return emails
   */
  @javax.annotation.Nonnull
  public List<String> getEmails() {
    return emails;
  }

  public void setEmails(@javax.annotation.Nonnull List<String> emails) {
    this.emails = emails;
  }


  public ScheduleEmailCampaignRequestRecipients groupIds(@javax.annotation.Nonnull List<Integer> groupIds) {
    this.groupIds = groupIds;
    return this;
  }

  public ScheduleEmailCampaignRequestRecipients addGroupIdsItem(Integer groupIdsItem) {
    if (this.groupIds == null) {
      this.groupIds = new ArrayList<>();
    }
    this.groupIds.add(groupIdsItem);
    return this;
  }

  /**
   * Array of group IDs to send to.
   * @return groupIds
   */
  @javax.annotation.Nonnull
  public List<Integer> getGroupIds() {
    return groupIds;
  }

  public void setGroupIds(@javax.annotation.Nonnull List<Integer> groupIds) {
    this.groupIds = groupIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleEmailCampaignRequestRecipients scheduleEmailCampaignRequestRecipients = (ScheduleEmailCampaignRequestRecipients) o;
    return Objects.equals(this.contactIds, scheduleEmailCampaignRequestRecipients.contactIds) &&
        Objects.equals(this.emails, scheduleEmailCampaignRequestRecipients.emails) &&
        Objects.equals(this.groupIds, scheduleEmailCampaignRequestRecipients.groupIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactIds, emails, groupIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleEmailCampaignRequestRecipients {\n");
    sb.append("    contactIds: ").append(toIndentedString(contactIds)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    groupIds: ").append(toIndentedString(groupIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("contactIds", "emails", "groupIds"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("contactIds", "emails", "groupIds"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScheduleEmailCampaignRequestRecipients
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScheduleEmailCampaignRequestRecipients.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ScheduleEmailCampaignRequestRecipients is not found in the empty JSON string", ScheduleEmailCampaignRequestRecipients.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ScheduleEmailCampaignRequestRecipients.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ScheduleEmailCampaignRequestRecipients` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ScheduleEmailCampaignRequestRecipients.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("contactIds") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("contactIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `contactIds` to be an array in the JSON string but got `%s`", jsonObj.get("contactIds").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("emails") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("emails").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `emails` to be an array in the JSON string but got `%s`", jsonObj.get("emails").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("groupIds") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("groupIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `groupIds` to be an array in the JSON string but got `%s`", jsonObj.get("groupIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScheduleEmailCampaignRequestRecipients.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScheduleEmailCampaignRequestRecipients' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScheduleEmailCampaignRequestRecipients> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScheduleEmailCampaignRequestRecipients.class));

       return (TypeAdapter<T>) new TypeAdapter<ScheduleEmailCampaignRequestRecipients>() {
           @Override
           public void write(JsonWriter out, ScheduleEmailCampaignRequestRecipients value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScheduleEmailCampaignRequestRecipients read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScheduleEmailCampaignRequestRecipients given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScheduleEmailCampaignRequestRecipients
   * @throws IOException if the JSON string is invalid with respect to ScheduleEmailCampaignRequestRecipients
   */
  public static ScheduleEmailCampaignRequestRecipients fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScheduleEmailCampaignRequestRecipients.class);
  }

  /**
   * Convert an instance of ScheduleEmailCampaignRequestRecipients to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

