/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * UpdateSurveyCountryItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class UpdateSurveyCountryItem {
  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nonnull
  private String country;

  public static final String SERIALIZED_NAME_USER_INBOUND_ID = "userInboundId";
  @SerializedName(SERIALIZED_NAME_USER_INBOUND_ID)
  @javax.annotation.Nonnull
  private Integer userInboundId;

  public UpdateSurveyCountryItem() {
  }

  public UpdateSurveyCountryItem country(@javax.annotation.Nonnull String country) {
    this.country = country;
    return this;
  }

  /**
   * The 2-letter ISO country code.
   * @return country
   */
  @javax.annotation.Nonnull
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nonnull String country) {
    this.country = country;
  }


  public UpdateSurveyCountryItem userInboundId(@javax.annotation.Nonnull Integer userInboundId) {
    this.userInboundId = userInboundId;
    return this;
  }

  /**
   * User inbound phone ID.
   * @return userInboundId
   */
  @javax.annotation.Nonnull
  public Integer getUserInboundId() {
    return userInboundId;
  }

  public void setUserInboundId(@javax.annotation.Nonnull Integer userInboundId) {
    this.userInboundId = userInboundId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateSurveyCountryItem updateSurveyCountryItem = (UpdateSurveyCountryItem) o;
    return Objects.equals(this.country, updateSurveyCountryItem.country) &&
        Objects.equals(this.userInboundId, updateSurveyCountryItem.userInboundId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, userInboundId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateSurveyCountryItem {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    userInboundId: ").append(toIndentedString(userInboundId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("country", "userInboundId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("country", "userInboundId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateSurveyCountryItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateSurveyCountryItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in UpdateSurveyCountryItem is not found in the empty JSON string", UpdateSurveyCountryItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateSurveyCountryItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UpdateSurveyCountryItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateSurveyCountryItem.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateSurveyCountryItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateSurveyCountryItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateSurveyCountryItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateSurveyCountryItem.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateSurveyCountryItem>() {
           @Override
           public void write(JsonWriter out, UpdateSurveyCountryItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateSurveyCountryItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateSurveyCountryItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateSurveyCountryItem
   * @throws IOException if the JSON string is invalid with respect to UpdateSurveyCountryItem
   */
  public static UpdateSurveyCountryItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateSurveyCountryItem.class);
  }

  /**
   * Convert an instance of UpdateSurveyCountryItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

