/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.textmagic.sdk.model.CustomFieldListItem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * UpdateContactRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class UpdateContactRequest {
  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  @javax.annotation.Nullable
  private String firstName;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  @javax.annotation.Nullable
  private String lastName;

  public static final String SERIALIZED_NAME_PHONE = "phone";
  @SerializedName(SERIALIZED_NAME_PHONE)
  @javax.annotation.Nullable
  private String phone;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_COMPANY_NAME = "companyName";
  @SerializedName(SERIALIZED_NAME_COMPANY_NAME)
  @javax.annotation.Nullable
  private String companyName;

  public static final String SERIALIZED_NAME_LISTS = "lists";
  @SerializedName(SERIALIZED_NAME_LISTS)
  @javax.annotation.Nullable
  private String lists;

  public static final String SERIALIZED_NAME_FAVORITED = "favorited";
  @SerializedName(SERIALIZED_NAME_FAVORITED)
  @javax.annotation.Nullable
  private Boolean favorited;

  public static final String SERIALIZED_NAME_BLOCKED = "blocked";
  @SerializedName(SERIALIZED_NAME_BLOCKED)
  @javax.annotation.Nullable
  private Boolean blocked;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private Integer type;

  public static final String SERIALIZED_NAME_CUSTOM_FIELD_VALUES = "customFieldValues";
  @SerializedName(SERIALIZED_NAME_CUSTOM_FIELD_VALUES)
  @javax.annotation.Nullable
  private List<CustomFieldListItem> customFieldValues = new ArrayList<>();

  public static final String SERIALIZED_NAME_LOCAL = "local";
  @SerializedName(SERIALIZED_NAME_LOCAL)
  @javax.annotation.Nullable
  private Integer local;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nullable
  private String country;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<Integer> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  @javax.annotation.Nullable
  private Integer owner;

  public UpdateContactRequest() {
  }

  public UpdateContactRequest firstName(@javax.annotation.Nullable String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Contact first name.
   * @return firstName
   */
  @javax.annotation.Nullable
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(@javax.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }


  public UpdateContactRequest lastName(@javax.annotation.Nullable String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Contact last name.
   * @return lastName
   */
  @javax.annotation.Nullable
  public String getLastName() {
    return lastName;
  }

  public void setLastName(@javax.annotation.Nullable String lastName) {
    this.lastName = lastName;
  }


  public UpdateContactRequest phone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
    return this;
  }

  /**
   * Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
   * @return phone
   */
  @javax.annotation.Nullable
  public String getPhone() {
    return phone;
  }

  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public UpdateContactRequest email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Contact email address.
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public UpdateContactRequest companyName(@javax.annotation.Nullable String companyName) {
    this.companyName = companyName;
    return this;
  }

  /**
   * Contact company name.
   * @return companyName
   */
  @javax.annotation.Nullable
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(@javax.annotation.Nullable String companyName) {
    this.companyName = companyName;
  }


  public UpdateContactRequest lists(@javax.annotation.Nullable String lists) {
    this.lists = lists;
    return this;
  }

  /**
   * Comma-separated [list](https://docs.textmagic.com/#section/Lists) ID. Each contact must be assigned to at least one list.
   * @return lists
   */
  @javax.annotation.Nullable
  public String getLists() {
    return lists;
  }

  public void setLists(@javax.annotation.Nullable String lists) {
    this.lists = lists;
  }


  public UpdateContactRequest favorited(@javax.annotation.Nullable Boolean favorited) {
    this.favorited = favorited;
    return this;
  }

  /**
   * Is the contact marked as favorite?
   * @return favorited
   */
  @javax.annotation.Nullable
  public Boolean getFavorited() {
    return favorited;
  }

  public void setFavorited(@javax.annotation.Nullable Boolean favorited) {
    this.favorited = favorited;
  }


  public UpdateContactRequest blocked(@javax.annotation.Nullable Boolean blocked) {
    this.blocked = blocked;
    return this;
  }

  /**
   * Is the contact blocked for outgoing and incoming messaging?
   * @return blocked
   */
  @javax.annotation.Nullable
  public Boolean getBlocked() {
    return blocked;
  }

  public void setBlocked(@javax.annotation.Nullable Boolean blocked) {
    this.blocked = blocked;
  }


  public UpdateContactRequest type(@javax.annotation.Nullable Integer type) {
    this.type = type;
    return this;
  }

  /**
   * Force type of phone. Possible values: 0 is landline; 1 is mobile; default is -1 (auto-detection).
   * @return type
   */
  @javax.annotation.Nullable
  public Integer getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable Integer type) {
    this.type = type;
  }


  public UpdateContactRequest customFieldValues(@javax.annotation.Nullable List<CustomFieldListItem> customFieldValues) {
    this.customFieldValues = customFieldValues;
    return this;
  }

  public UpdateContactRequest addCustomFieldValuesItem(CustomFieldListItem customFieldValuesItem) {
    if (this.customFieldValues == null) {
      this.customFieldValues = new ArrayList<>();
    }
    this.customFieldValues.add(customFieldValuesItem);
    return this;
  }

  /**
   * Get customFieldValues
   * @return customFieldValues
   */
  @javax.annotation.Nullable
  public List<CustomFieldListItem> getCustomFieldValues() {
    return customFieldValues;
  }

  public void setCustomFieldValues(@javax.annotation.Nullable List<CustomFieldListItem> customFieldValues) {
    this.customFieldValues = customFieldValues;
  }


  public UpdateContactRequest local(@javax.annotation.Nullable Integer local) {
    this.local = local;
    return this;
  }

  /**
   * Treat phone numbers passed in the request body as **local**.
   * @return local
   */
  @javax.annotation.Nullable
  public Integer getLocal() {
    return local;
  }

  public void setLocal(@javax.annotation.Nullable Integer local) {
    this.local = local;
  }


  public UpdateContactRequest country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * The 2-letter ISO country code for local phone numbers, used when **local** is set to true.
   * @return country
   */
  @javax.annotation.Nullable
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public UpdateContactRequest tags(@javax.annotation.Nullable List<Integer> tags) {
    this.tags = tags;
    return this;
  }

  public UpdateContactRequest addTagsItem(Integer tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * An array of tag IDs that will be assigned to the contact.
   * @return tags
   */
  @javax.annotation.Nullable
  public List<Integer> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<Integer> tags) {
    this.tags = tags;
  }


  public UpdateContactRequest owner(@javax.annotation.Nullable Integer owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Contact Owner ID
   * @return owner
   */
  @javax.annotation.Nullable
  public Integer getOwner() {
    return owner;
  }

  public void setOwner(@javax.annotation.Nullable Integer owner) {
    this.owner = owner;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateContactRequest updateContactRequest = (UpdateContactRequest) o;
    return Objects.equals(this.firstName, updateContactRequest.firstName) &&
        Objects.equals(this.lastName, updateContactRequest.lastName) &&
        Objects.equals(this.phone, updateContactRequest.phone) &&
        Objects.equals(this.email, updateContactRequest.email) &&
        Objects.equals(this.companyName, updateContactRequest.companyName) &&
        Objects.equals(this.lists, updateContactRequest.lists) &&
        Objects.equals(this.favorited, updateContactRequest.favorited) &&
        Objects.equals(this.blocked, updateContactRequest.blocked) &&
        Objects.equals(this.type, updateContactRequest.type) &&
        Objects.equals(this.customFieldValues, updateContactRequest.customFieldValues) &&
        Objects.equals(this.local, updateContactRequest.local) &&
        Objects.equals(this.country, updateContactRequest.country) &&
        Objects.equals(this.tags, updateContactRequest.tags) &&
        Objects.equals(this.owner, updateContactRequest.owner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, phone, email, companyName, lists, favorited, blocked, type, customFieldValues, local, country, tags, owner);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateContactRequest {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    lists: ").append(toIndentedString(lists)).append("\n");
    sb.append("    favorited: ").append(toIndentedString(favorited)).append("\n");
    sb.append("    blocked: ").append(toIndentedString(blocked)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    customFieldValues: ").append(toIndentedString(customFieldValues)).append("\n");
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("firstName", "lastName", "phone", "email", "companyName", "lists", "favorited", "blocked", "type", "customFieldValues", "local", "country", "tags", "owner"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateContactRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateContactRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in UpdateContactRequest is not found in the empty JSON string", UpdateContactRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateContactRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UpdateContactRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("firstName") != null && !jsonObj.get("firstName").isJsonNull()) && !jsonObj.get("firstName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `firstName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstName").toString()));
      }
      if ((jsonObj.get("lastName") != null && !jsonObj.get("lastName").isJsonNull()) && !jsonObj.get("lastName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `lastName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastName").toString()));
      }
      if ((jsonObj.get("phone") != null && !jsonObj.get("phone").isJsonNull()) && !jsonObj.get("phone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `phone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("phone").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("companyName") != null && !jsonObj.get("companyName").isJsonNull()) && !jsonObj.get("companyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `companyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyName").toString()));
      }
      if ((jsonObj.get("lists") != null && !jsonObj.get("lists").isJsonNull()) && !jsonObj.get("lists").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `lists` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lists").toString()));
      }
      if (jsonObj.get("customFieldValues") != null && !jsonObj.get("customFieldValues").isJsonNull()) {
        JsonArray jsonArraycustomFieldValues = jsonObj.getAsJsonArray("customFieldValues");
        if (jsonArraycustomFieldValues != null) {
          // ensure the json data is an array
          if (!jsonObj.get("customFieldValues").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `customFieldValues` to be an array in the JSON string but got `%s`", jsonObj.get("customFieldValues").toString()));
          }

          // validate the optional field `customFieldValues` (array)
          for (int i = 0; i < jsonArraycustomFieldValues.size(); i++) {
            CustomFieldListItem.validateJsonElement(jsonArraycustomFieldValues.get(i));
          };
        }
      }
      if ((jsonObj.get("country") != null && !jsonObj.get("country").isJsonNull()) && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateContactRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateContactRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateContactRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateContactRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateContactRequest>() {
           @Override
           public void write(JsonWriter out, UpdateContactRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateContactRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateContactRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateContactRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateContactRequest
   */
  public static UpdateContactRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateContactRequest.class);
  }

  /**
   * Convert an instance of UpdateContactRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

