/*
 * Textmagic API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.textmagic.sdk.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.textmagic.sdk.JSON;

/**
 * UpdateInboundMessagesNotificationSettingsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class UpdateInboundMessagesNotificationSettingsRequest {
  public static final String SERIALIZED_NAME_INBOUND_MESSAGE_NOTIFICATION = "inboundMessageNotification";
  @SerializedName(SERIALIZED_NAME_INBOUND_MESSAGE_NOTIFICATION)
  @javax.annotation.Nullable
  private Boolean inboundMessageNotification;

  public static final String SERIALIZED_NAME_INCLUDE_SMS_HISTORY = "includeSmsHistory";
  @SerializedName(SERIALIZED_NAME_INCLUDE_SMS_HISTORY)
  @javax.annotation.Nullable
  private Boolean includeSmsHistory;

  public static final String SERIALIZED_NAME_SEND_IN_HTML_FORMAT = "sendInHtmlFormat";
  @SerializedName(SERIALIZED_NAME_SEND_IN_HTML_FORMAT)
  @javax.annotation.Nullable
  private Boolean sendInHtmlFormat;

  public static final String SERIALIZED_NAME_ALERT_EMAIL1 = "alertEmail1";
  @SerializedName(SERIALIZED_NAME_ALERT_EMAIL1)
  @javax.annotation.Nullable
  private String alertEmail1;

  public static final String SERIALIZED_NAME_ALERT_EMAIL2 = "alertEmail2";
  @SerializedName(SERIALIZED_NAME_ALERT_EMAIL2)
  @javax.annotation.Nullable
  private String alertEmail2;

  public static final String SERIALIZED_NAME_ALERT_EMAIL3 = "alertEmail3";
  @SerializedName(SERIALIZED_NAME_ALERT_EMAIL3)
  @javax.annotation.Nullable
  private String alertEmail3;

  public UpdateInboundMessagesNotificationSettingsRequest() {
  }

  public UpdateInboundMessagesNotificationSettingsRequest inboundMessageNotification(@javax.annotation.Nullable Boolean inboundMessageNotification) {
    this.inboundMessageNotification = inboundMessageNotification;
    return this;
  }

  /**
   * Should user receive notification about new incoming messages.
   * @return inboundMessageNotification
   */
  @javax.annotation.Nullable
  public Boolean getInboundMessageNotification() {
    return inboundMessageNotification;
  }

  public void setInboundMessageNotification(@javax.annotation.Nullable Boolean inboundMessageNotification) {
    this.inboundMessageNotification = inboundMessageNotification;
  }


  public UpdateInboundMessagesNotificationSettingsRequest includeSmsHistory(@javax.annotation.Nullable Boolean includeSmsHistory) {
    this.includeSmsHistory = includeSmsHistory;
    return this;
  }

  /**
   * Include SMS history into notification Email.
   * @return includeSmsHistory
   */
  @javax.annotation.Nullable
  public Boolean getIncludeSmsHistory() {
    return includeSmsHistory;
  }

  public void setIncludeSmsHistory(@javax.annotation.Nullable Boolean includeSmsHistory) {
    this.includeSmsHistory = includeSmsHistory;
  }


  public UpdateInboundMessagesNotificationSettingsRequest sendInHtmlFormat(@javax.annotation.Nullable Boolean sendInHtmlFormat) {
    this.sendInHtmlFormat = sendInHtmlFormat;
    return this;
  }

  /**
   * Send Email notification in HTML format.
   * @return sendInHtmlFormat
   */
  @javax.annotation.Nullable
  public Boolean getSendInHtmlFormat() {
    return sendInHtmlFormat;
  }

  public void setSendInHtmlFormat(@javax.annotation.Nullable Boolean sendInHtmlFormat) {
    this.sendInHtmlFormat = sendInHtmlFormat;
  }


  public UpdateInboundMessagesNotificationSettingsRequest alertEmail1(@javax.annotation.Nullable String alertEmail1) {
    this.alertEmail1 = alertEmail1;
    return this;
  }

  /**
   * New message notification email 2.
   * @return alertEmail1
   */
  @javax.annotation.Nullable
  public String getAlertEmail1() {
    return alertEmail1;
  }

  public void setAlertEmail1(@javax.annotation.Nullable String alertEmail1) {
    this.alertEmail1 = alertEmail1;
  }


  public UpdateInboundMessagesNotificationSettingsRequest alertEmail2(@javax.annotation.Nullable String alertEmail2) {
    this.alertEmail2 = alertEmail2;
    return this;
  }

  /**
   * New message notification email 2.
   * @return alertEmail2
   */
  @javax.annotation.Nullable
  public String getAlertEmail2() {
    return alertEmail2;
  }

  public void setAlertEmail2(@javax.annotation.Nullable String alertEmail2) {
    this.alertEmail2 = alertEmail2;
  }


  public UpdateInboundMessagesNotificationSettingsRequest alertEmail3(@javax.annotation.Nullable String alertEmail3) {
    this.alertEmail3 = alertEmail3;
    return this;
  }

  /**
   * New message notification email 3.
   * @return alertEmail3
   */
  @javax.annotation.Nullable
  public String getAlertEmail3() {
    return alertEmail3;
  }

  public void setAlertEmail3(@javax.annotation.Nullable String alertEmail3) {
    this.alertEmail3 = alertEmail3;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateInboundMessagesNotificationSettingsRequest updateInboundMessagesNotificationSettingsRequest = (UpdateInboundMessagesNotificationSettingsRequest) o;
    return Objects.equals(this.inboundMessageNotification, updateInboundMessagesNotificationSettingsRequest.inboundMessageNotification) &&
        Objects.equals(this.includeSmsHistory, updateInboundMessagesNotificationSettingsRequest.includeSmsHistory) &&
        Objects.equals(this.sendInHtmlFormat, updateInboundMessagesNotificationSettingsRequest.sendInHtmlFormat) &&
        Objects.equals(this.alertEmail1, updateInboundMessagesNotificationSettingsRequest.alertEmail1) &&
        Objects.equals(this.alertEmail2, updateInboundMessagesNotificationSettingsRequest.alertEmail2) &&
        Objects.equals(this.alertEmail3, updateInboundMessagesNotificationSettingsRequest.alertEmail3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inboundMessageNotification, includeSmsHistory, sendInHtmlFormat, alertEmail1, alertEmail2, alertEmail3);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateInboundMessagesNotificationSettingsRequest {\n");
    sb.append("    inboundMessageNotification: ").append(toIndentedString(inboundMessageNotification)).append("\n");
    sb.append("    includeSmsHistory: ").append(toIndentedString(includeSmsHistory)).append("\n");
    sb.append("    sendInHtmlFormat: ").append(toIndentedString(sendInHtmlFormat)).append("\n");
    sb.append("    alertEmail1: ").append(toIndentedString(alertEmail1)).append("\n");
    sb.append("    alertEmail2: ").append(toIndentedString(alertEmail2)).append("\n");
    sb.append("    alertEmail3: ").append(toIndentedString(alertEmail3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("inboundMessageNotification", "includeSmsHistory", "sendInHtmlFormat", "alertEmail1", "alertEmail2", "alertEmail3"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateInboundMessagesNotificationSettingsRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateInboundMessagesNotificationSettingsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in UpdateInboundMessagesNotificationSettingsRequest is not found in the empty JSON string", UpdateInboundMessagesNotificationSettingsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateInboundMessagesNotificationSettingsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UpdateInboundMessagesNotificationSettingsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("alertEmail1") != null && !jsonObj.get("alertEmail1").isJsonNull()) && !jsonObj.get("alertEmail1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `alertEmail1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alertEmail1").toString()));
      }
      if ((jsonObj.get("alertEmail2") != null && !jsonObj.get("alertEmail2").isJsonNull()) && !jsonObj.get("alertEmail2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `alertEmail2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alertEmail2").toString()));
      }
      if ((jsonObj.get("alertEmail3") != null && !jsonObj.get("alertEmail3").isJsonNull()) && !jsonObj.get("alertEmail3").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `alertEmail3` to be a primitive type in the JSON string but got `%s`", jsonObj.get("alertEmail3").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateInboundMessagesNotificationSettingsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateInboundMessagesNotificationSettingsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateInboundMessagesNotificationSettingsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateInboundMessagesNotificationSettingsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateInboundMessagesNotificationSettingsRequest>() {
           @Override
           public void write(JsonWriter out, UpdateInboundMessagesNotificationSettingsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateInboundMessagesNotificationSettingsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateInboundMessagesNotificationSettingsRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateInboundMessagesNotificationSettingsRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateInboundMessagesNotificationSettingsRequest
   */
  public static UpdateInboundMessagesNotificationSettingsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateInboundMessagesNotificationSettingsRequest.class);
  }

  /**
   * Convert an instance of UpdateInboundMessagesNotificationSettingsRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

